### ISSUE TITLE
Any way to add dynamically annotation ?

### ISSUE THREAD

**Issue by ybarbaria** [chartjs/chartjs-plugin-annotation#103]
Hello, 

I try to add annotation dynamically. My chart exist and during the life of my chart I would like to add an annotation (to hilight area of point). There is any solution to do that ? Without redraw all the chart? 

Thx

**Comment by nullpointer77** [comment]
From my understanding that isn't the way that chart.js works.  If you wanted functionality like this then you probably need to bring it up with chart.js and not the annotation plugin.

**Comment by alex-martinez** [comment]
@ybarbaria that probably can't be done due to the way canvas draws elements in layers. Maybe turning off animations will help? Your chart will still redraw, but it will be less noticeable.

**Comment by kmm2908** [comment]
I too need to draw lines on a chart that I already add data to dynamically.
If I set the automation options and then call chart.update() will this draw lines dynamically?

**Comment by RinonNinqueon** [comment]
Something like this:
```
function addAnnotationVertical(date_time, text)
{
	var line = 'line' + date_time;
	lineChart.options.annotation.annotations.push(
		{
			drawTime: "afterDatasetsDraw",
			id: line,
			type: "line",
			mode: "vertical",
			scaleID: "x-axis-0",
			value: date_time, 
			borderColor: "black",
			borderWidth: 1,
			label:
			{
				fontColor: "black",
				backgroundColor: "white",
				content: text,
				enabled: true
			}
		});
	lineChart.update();
}
```
Where lineChart is your "new Chart" object.
It works for me. Also with streaming plugin.

**Comment by afh13** [comment]
Don't use id in annotation and work fine. My code exmpale is:

var eventArea: any = {
        type: 'box',
        xScaleID: 'x-axis-0',
        yScaleID: 'satAxis',
        xMax: this.secondsToTime.transform(event.sessionSecondTriggered),
        xMin: this.secondsToTime.transform(event.sessionSecondTriggered),
        yMax: 101,
        yMin: 49,
        borderColor: '#FFFFFF',
        borderWidth: 2,        
      };
      this.chart.chart.options.annotation.annotations.push(eventArea);

**Comment by etimberg** [comment]
Closing as this behaviour is as-designed. Redraws must occur because of chart.js uses the canvas

**Comment by denglish357** [comment]
Just declare an array outside of the plugin to store the points you want to draw and in the mousemove function redraw the points from that array on every frame.

**Comment by gcormier9** [comment]
Hi there,

I am new to chartjs and I was wondering if anyone can shed some lights on this old topic.
Is it possible it is no longer possible to dynamically add annotation using chart.options.annotation.annotations.push?
I am trying it here: https://jsfiddle.net/84gd7jr0/

I'll appreciate if anyone can help!
Best regards

**Comment by stockiNail** [comment]
@gcormier9 maybe you remove the post.. 

About 
> Is it possible it is no longer possible to dynamically add annotation using chart.options.annotation.annotations.push?

Even if it works, it's better to add the plugin annotations in the `chart.options.plugins.[pluginId]` namespace, for this plugin  `chart.options.plugins.annotation`.

**Comment by gcormier9** [comment]
Hi @stockiNail,

Yes I did remove the post as I figured it out... However, I have noted the syntax has changed a bit. Instead of
`chart.options.annotation.annotations.push()` or `chart.options.plugins.annotation.annotations.push()`, we have to use `chart.options.plugins.annotation.annotations['newAnnotation'] = {}`

https://jsfiddle.net/tmbwcjgh/

Regards,

**Comment by stockiNail** [comment]
@gcormier9 sorry for my late reply but I was busy in other stuff.

The `annotations` can be set by an object (as you described in your sample) or by an array.
You can use an array if it's more efficient for your use case.

See here:  https://codepen.io/stockinail/pen/oNormBX

**Comment by gcormier9** [comment]
Good to know! Thanks @stockiNail for the quick reply!
