### ISSUE TITLE
Box is not correct on multiple labels (x-axis ticks).

### ISSUE THREAD

**Issue by adeel3612** [chartjs/chartjs-plugin-annotation#104]
I am drawing a box on a line chart. I am having a problem when i dram the box and give it a `xMax`. It did not draw on the last point if the points are multiple, instead it draw on the first point. For example. i have labels `[12-Mar-2017, 13-Mar-2017, 14-Mar-2017,15-Mar-2017,15-Mar-2017]`. Notice here that `15-Mar-2017` is two times. If i want to draw a box from `13-Mar to 15-Mar` It will only highlight the first `15-Mar-2017` Point not the next. Is there any solution for this ?

This is the [jsFiddle](https://jsfiddle.net/8zm3ejj0/)

Any kind of help would be much appreciated.

**Comment by etimberg** [comment]
In v1.0.0-beta.4 you pass the index as the value so this is resolved. See https://jsfiddle.net/prmnh1v3/2/
