### ISSUE TITLE
Line not appearing with integer value

### ISSUE THREAD

**Issue by okaymaged** [chartjs/chartjs-plugin-annotation#106]
Please see this [example](https://codepen.io/anon/pen/QaQWba). The vertical line annotation works if I set the `value` to string `MAR`, matching the label, but if I set it to an integer x-index (such as `2` in the example), the vertical line does not appear.

**Comment by okaymaged** [comment]
Issue resolved by setting axis type to 'linear'.

**Comment by curiousPup** [comment]
can you please explain the solution? I'm trying to fix the same thing
