### ISSUE TITLE
Label content restricted within graph space

### ISSUE THREAD

**Issue by Pwntus** [chartjs/chartjs-plugin-annotation#110]
I use this plugin to create horizontal annotations to mark non-linear thresholds on a line graph (apparently Chart.js only allows fixed steps for an axis).

The problem I run into is that the label content/text gets clipped once I adjust it's position to extend past an axis, using the `xAdjust` option.

[Demo Fiddle](https://jsfiddle.net/8zm3ejj0/1/)

Is this something that could be "fixed"? Thoughts?

**Comment by sathyesh** [comment]
Any fix? Same thing is happening for Y axis when I give negative yAdjust.

**Comment by kurkle** [comment]
Not an issue with v1 anymore: https://jsfiddle.net/q5xzjcpm/
