### ISSUE TITLE
cannot load the annotation plugin as AMD module for require JS

### ISSUE THREAD

**Issue by overwatch13** [chartjs/chartjs-plugin-annotation#111]
I am using requireJS on my website, so everything needs to be referenced, and than included via regular AMD. Is it not possible with this library?

![annotation](https://user-images.githubusercontent.com/8516191/36561571-0a65f160-17e2-11e8-962a-ef35904c2003.PNG)

**Comment by kmm2908** [comment]
I have same issue when trying to use with require.js.
Get this error:
annotation.js:468 Uncaught TypeError: Cannot read property 'Annotation' of undefined
    at Object.6../annotation.js (annotation.js:468)
    at s (annotation.js:10)
    at e (annotation.js:10)
    at annotation

**Comment by lizeidsness** [comment]
I have the same problem without require.js, with Dojo and TypeScript which are loading AMD style. Annotation plugin has to be loaded after Chart.  If I force load them in my HTML first, as <script tags, it works ok.  Would really like it to load asynchronously.

**Comment by etimberg** [comment]
Well out of date and the build system has changed significantly since then
