### ISSUE TITLE
updates.html sample does not work

### ISSUE THREAD

**Issue by robotloveskitten** [chartjs/chartjs-plugin-annotation#113]
I've been trying to duplicate this functionality -- add annotations dynamically and update chart, but haven't gotten it to work. Now I see the sample doesn't work anymore either. 

switching the example to use 2.6.0 from the CDN does work.

**Comment by jgadbois** [comment]
I'm also trying to dynamically add/remove lines and not seeing it update

**Comment by osro** [comment]
This is probably due to changes how 2.7.0 ChartJS copies configs once you create the chart. Earlier it was references.

You need to work your changes directly to the chart.options and after that call chart.update().
 
https://github.com/chartjs/Chart.js/issues/5111#issuecomment-355934167

**Comment by jellisii** [comment]
Could a working example be demonstrated in a codepen?  I've been struggling with this, and while I can remove annotations easily enough, adding them has been elusive.
```javascript
$('.toggle_annotation').on('click', function() {
    if ($(this).prop('checked')) {
        // this works as expected.  After calling update(), the 
        // first annotation in the list is removed.
        myChart.options.annotation.annotations.splice(0, 1);
    } else {
        // this does not. The pushed annotation does not appear 
        // on the chart.  
        myChart.config.options.annotation.annotations.push({
            type: 'line',
            mode: 'horizontal',
            scaleID: 'y-axis-1',
            value: randomScalingFactor() * 3,
            borderColor: randomColor(0.75),
            borderWidth: 5
        });
    }
    myChart.update();
}
```

**Comment by etimberg** [comment]
The latest code in master is working with chart.js v3.0.0-beta.13
