### ISSUE TITLE
Read options from dedicated plugins section

### ISSUE THREAD

**Issue by alllex** [chartjs/chartjs-plugin-annotation#114]
According to [Chart.js docs](http://www.chartjs.org/docs/latest/developers/plugins.html#plugin-options) all plugins should read options from dedicated `options.plugins.<plugin_name>` section. However, this plugin reads its options straight from `options.<plugin_name>`.

This makes it difficult to work with the plugin from TypeScript where in [declared types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts) it is not reasonable to add options per plugin. There is, however, a convenient `plugins?: any;`.

I guess it is not possible to stop reading options from `options.annotation` due to compatibility issues. One of possible workarounds is to check if `options.plugins.annotation` is present and **also** read from there.

**Comment by KayHS** [comment]
Im also having trouble using @types/chart.js with this plugin now.

` error TS2345: Argument of type '{ type: string; data: { labels: string[]; datasets: { fill: true; lineTension: number; pointRadiu...' is not assignable to parameter of type 'ChartConfiguration'.
  Types of property 'options' are incompatible.
    Type '{ plugins: { datalabels: { display: boolean; }; }; legend: { display: false; }; annotation: { ann...' is not assignable to type 'ChartOptions'.
      Object literal may only specify known properties, but 'annotation' does not exist in type 'ChartOptions'. Did you mean to write 'rotation'?`

**Comment by sfentress** [comment]
Any chance of getting a release bump, so we can pull this in with npm?

**Comment by benmccann** [comment]
I don't think I have permission to `npm publish`. Perhaps you could ask someone in the #dev slack channel to cut a release

**Comment by KayHS** [comment]
Has this been fixed?
