### ISSUE TITLE
Does it work with chartjs-node ?

### ISSUE THREAD

**Issue by Mathieu-R** [chartjs/chartjs-plugin-annotation#117]
I'm trying to make this work with chartjs-node but it doesn't draw anything on my chart. 
However I do not have any errors.

```js
...
data: {...}
options: {
  ...
  annotation: {
    annotations: [{
      type: 'line',
      mode: 'horizontal',
      borderColor: '#D2DAE2',
      borderWidth: 1,
      borderDash: [2, 2],
      value: best.value,
      label: {
        content: 'Best time'
      }
  }, {
     type: 'line',
     mode: 'vertical',
     borderColor: '#D2DAE2',
     borderWidth: 1,
     borderDash: [2, 2],
     value: xLabels[best.index],
     label: {
       content: 'Best time'
     }
   }]
  }
}
```

Thanks in advance !

**Comment by Mathieu-R** [comment]
Yeah it works. 
I just forgot to add `scaleID`property.

**Comment by kavikumarsah** [comment]
Hi @Mathieu-R I'm facing the same issue as you're facing after add scaleID too.
I think I'm doing something wrong. Can post your whole code?
I know it's too late see if you can help.
thanks in advance

**Comment by Striderown** [comment]
I faced this issue as well, I managed to fix it like this:

    const ChartjsNode = require('chartjs-node');
    const chartjs_annotation = require('chartjs-plugin-annotation');

    var chartNode = new ChartjsNode(width, height);
    chartNode.on('beforeDraw', function (Chartjs) {

        // Register the annotation plugin
        Chartjs.plugins.register( chartjs_annotation );
    });
    
    chartNode.drawChart( <your_chartjs_configuration> )
    .then( function(){
        // Save as testimage.png
        chartNode.writeImageToFile('image/png', './testimage.png'); 
    });


And your configuration (example):

    type: 'line',
    data: {
        ...
    },
    options: {
        ...
        annotation: {
            annotations: [{
                value: 100,
                type: 'line',
                mode: 'horizontal',
                scaleID: 'y-axis-0',
                borderColor: '#D2DAE2',
                borderWidth: 1,
                borderDash: [2, 2],
                label: {
                    content: 'Value 1'
                }
            }, {
                value: 50
                type: 'line',
                mode: 'horizontal',
                scaleID: 'y-axis-0',
                borderColor: '#D2DAE2',
                borderWidth: 1,
                borderDash: [2, 2],
                value: 500,
                label: {
                    content: 'Value 2'
                 }
            }]
        }

Hope this helps you aswell

**Comment by kavikumarsah** [comment]
Yeah Thanks @Striderown it's working
