### ISSUE TITLE
Enable labels to draw outside the chart area

### ISSUE THREAD

**Issue by nicscap** [chartjs/chartjs-plugin-annotation#119]
Hello,
I'm having problems when displaying some labels on my chart, when they are too close to the charts borders. Labels are not showing entirely so i wonder how i can make them look nicer and within the boundaries.

I try to add a z-index on CSS but I don't know id or class or something else

[IMG]http://i65.tinypic.com/30l2cy1.png[/IMG]

I'll attach an image showing my issue on the first label

Thanks for your help in advance, and congratulations on this awesome plugin

**Comment by julienmonty** [comment]
@nicscap Did you find a solution ?

**Comment by mahentoo** [comment]
I have same problem. Any solution?

**Comment by ritzverma** [comment]
Try using yAdjust property.

{
                    drawTime: "afterDatasetsDraw",
                    id: "hline3",
                    type: "line",
                    mode: "horizontal",
                    scaleID: "y-axis-0",
                    value: upperLimit,
                    borderColor: "#C0504D",
                    borderWidth: 2,
                    label: {
                      backgroundColor: '#000',
                      fontColor: "#fff",
                      content: `Upper Control Limit: ${Math.floor(upperLimit)}`,
                      enabled: true,
                      yAxis: 50,
                      yAdjust: -10
                    },

**Comment by schmidtl4** [comment]
@ritzverma - the yAdjust (or xAdjust) work as needed, but it seems that if you want the label to sit outside the actual graph so its not hiding anything, it gets cut off.  In other words, there appears to be no gutter in which content can spill over into.  I've tried changing padding of the canvas and the containing element, but neither of these has any effect on this problem.  I do hope this gets fixed!

**Comment by kurkle** [comment]
You should add `layout` padding to the chart itself: https://www.chartjs.org/docs/latest/configuration/layout.html

**Comment by schmidtl4** [comment]
Sorry, @kurkle , but as I noted I've already played with the padding for the chart and it does not allow an annotation to spill over into the margin.  The image shows that the right hand label is supposed to say "M4" but is cut off.  The padding set for the image is 90 - plenty of room to accommodate the spill over.  Instead, its just cutoff.

![2021-04-23_17-24-22-929](https://user-images.githubusercontent.com/1418698/115941124-fafe9e00-a458-11eb-95d2-4c1a69eafd1a.png)

**Comment by Quirksmode** [comment]
I am having the exact same issue, I need to show a label just above the chart area, but anything outside the chart area gets cropped

**Comment by JeremieBergeron** [comment]
Same issue for me.

**Comment by JeremieBergeron** [comment]
@stockiNail I have try to add a clip, but it seems to change nothing.

Here is a [quickchart example](https://quickchart.io/sandbox/#%7B%22chart%22%3A%22%7B%5Cr%5Cn%5Cttype%3A%20%5C%22bar%5C%22%2C%5Cr%5Cn%5Ctdata%3A%20%7B%5Cr%5Cn%5Ct%5Ctlabels%3A%20%5B%5C%22Mon%5C%22%2C%20%5C%22Tue%5C%22%2C%20%5C%22Wed%5C%22%2C%20%5C%22Thu%5C%22%2C%20%5C%22Fri%5C%22%2C%20%5C%22Sat%5C%22%2C%20%5C%22Sun%5C%22%5D%2C%5Cr%5Cn%5Ct%5Ctdatasets%3A%20%5B%7B%5Cr%5Cn%5Ct%5Ct%5Ctlabel%3A%20%5C%22Money%5C%22%2C%5Cr%5Cn%5Ct%5Ct%5Ctdata%3A%20%5B18%2C%2012%2C%206%2C%209%2C%2012%2C%203%2C%209%5D%2C%5Cr%5Cn%5Ct%5Ct%5CtbackgroundColor%3A%20%5C%22rgba(255%2C%2026%2C%20104%2C%200.2)%5C%22%5Cr%5Cn%5Ct%5Ct%7D%5D%5Cr%5Cn%5Ct%7D%2C%5Cr%5Cn%5Ctoptions%3A%20%7B%5Cr%5Cn%5Ct%5Ctscales%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Cty%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ct%20%20beginAtZero%3A%20true%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Cttitle%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Cttext%3A%20%5C%22Dollars%5C%22%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%7D%5Cr%5Cn%5Ct%5Ct%5Ct%7D%2C%5Cr%5Cn%5Ct%5Ct%7D%2C%5Cr%5Cn%5Ct%5Ctplugins%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ctannotation%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ct%20%20clip%3A%20false%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ctannotations%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ctline1%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Cttype%3A%20'line'%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5CtyMin%3A%2018%20%2F%20100%20*%2070%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5CtyMax%3A%2018%20%2F%20100%20*%2070%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5CtborderColor%3A%20'rgb(255%2C%2099%2C%20132)'%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5CtborderWidth%3A%202%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5CtborderDash%3A%20%5B10%2C%2010%5D%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ctlabel%3A%20%7B%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%20%20enabled%3A%20true%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%20%20content%3A%20%5C%2270%25%5C%22%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%20%20position%3A%20'end'%2C%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%20%20xAdjust%3A%2020%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%7D%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%7D%5Cr%5Cn%5Ct%5Ct%5Ct%5Ct%7D%5Cr%5Cn%5Ct%5Ct%5Ct%7D%5Cr%5Cn%5Ct%5Ct%7D%5Cr%5Cn%5Ct%7D%2C%5Cr%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A300%2C%22version%22%3A%223%22%2C%22backgroundColor%22%3A%22%23fff%22%7D).

**Comment by natBizitza** [comment]
> > @stockiNail I have try to add a clip, but it seems to change nothing.
> 
> @JeremieBergeron you have to add the padding to the chart anyway, otherwise you don't have space in the canvas.
> 
> I have added the layout and the right padding (to have space) to chart options
> 
> ```js
> 	options: {
> 	  layout: {
> 	    padding: {
> 	      right: 20
> 	    }
> 	  },
> 	scales: {
> ```
> 
> Here is the result using your example:
> 
> ![image](https://user-images.githubusercontent.com/11741250/172185124-eb36bb0f-cf8d-4d72-8d26-dfd93cf4e1dc.png)

Thank you! The `clip`, `padding` and `yAdjust` made it work!
