### ISSUE TITLE
Need to put vertical line annotation between x-axis points, not on them

### ISSUE THREAD

**Issue by phil-w** [chartjs/chartjs-plugin-annotation#120]
There's a closed issue on this, but it doesn't solve the problem. 

Example: need to draw a vertical line between two bars on a chart to show where the median value is. This is easy for odd numbers of points (although that leaves the quartiles as problems). 

An annotation is required: cannot otherwise colour the bars as bar colour is already used.

**Comment by etimberg** [comment]
Same underlying issue as #98

**Comment by kurkle** [comment]
https://www.chartjs.org/chartjs-plugin-annotation/samples/charts/bar.html
