### ISSUE TITLE
Annotation in combination with zoom causes weird ticks

### ISSUE THREAD

**Issue by Evertvdw** [chartjs/chartjs-plugin-annotation#121]
Hi there,

There was a problem that has been bugging me for quite some time but I finally figured out what the problem is. I have graph which both uses the annotation plugin and the zoom plugin (chartjs-plugin-zoom). I have a vertical annotation in my chart which causes weird behaviour to the x-axis when you pan back in time. 

What I think happens is that with the calculation of the ticks the annotation is always taken into account even when it is outside of the visible window of time. What happens then is that the further you go back the less ticks become visible until you have 0 ticks visible, which is very annoying. Is there a way to somehow ignore out of view annotations when calculating the ticks for an axis?

Thanks!

**Comment by kurkle** [comment]
The [`adjustScaleRange` option](https://www.chartjs.org/chartjs-plugin-annotation/guide/types/line.html#configuration) should help working around the issue.
