### ISSUE TITLE
Y axis range is increasing when the window is resized

### ISSUE THREAD

**Issue by d9nny** [chartjs/chartjs-plugin-annotation#123]
Hey,

Initially the chart and annotations render perfectly, however when the window is resized, the Y axis range increases considerably. Without the annotations this doesn't happed. I think it might be happening because the bottom and top box annotations have no yMin and yMax values respectively (although it does say they're optional). Below are my annotation options and screenshots.

Any help would be greatly appreciated, cheers! 

`[
      {
         "type": "box",
         "xScaleID": "x-axis-0",
         "yScaleID": "y-axis-0",
         "backgroundColor": "rgba(55, 56, 71, .2)",
         "yMax": 20
 },
 {
        "type": "box",
        "xScaleID": "x-axis-0",
        "yScaleID": "y-axis-0",
        "backgroundColor": "rgba(55, 56, 71, .2)",
        "yMin": 100
    }
]`

![screen shot 2018-05-29 at 15 51 22](https://user-images.githubusercontent.com/14181629/40666723-56390390-6358-11e8-980b-df65c0e16485.png)

![screen shot 2018-05-29 at 15 51 51](https://user-images.githubusercontent.com/14181629/40666722-56103a0a-6358-11e8-9cf7-4e782e3a5b18.png)

**Comment by benshort** [comment]
I have seen the same issue.

I have created a fiddle that shows the issue...

https://jsfiddle.net/benshort/f27e49jt/2/

Try resizing the page to see the issue.

**Comment by kurkle** [comment]
Does not happen with v1 anymore: https://jsfiddle.net/g6ohzu48/
