### ISSUE TITLE
Cannot read property 'Annotation' of undefined

### ISSUE THREAD

**Issue by karthiksd9** [chartjs/chartjs-plugin-annotation#124]
I am using annotation in my MVC 5 application.
I am using following JS files in Bundle.js file.
1.   "~/Scripts/Chart.bundle.js",    (version : 2.7.2)
2.  "~/Scripts/chartjs-plugin-annotation.min.js" (version : 0.5.3)

And, here is my chart.js code:
```
var ChartOptions =
{
	responsive: true,
	maintainAspectRatio: true,
	
	scales: {
		yAxes: [{
			stacked: true,
			ticks: {
				beginAtZero: true
			}
		}]
	},
	tooltips: {
		mode: 'index',
		intersect: true
	},
	
	annotation: 
	{
		drawTime: 'afterDatasetsDraw',
		annotations: [{
			type: 'line',
			mode: 'horizontal',
			scaleID: 'y-axis-0',
			value: val,
			borderColor: 'green',
			borderWidth: 4,
			label: {
				enabled: true,
				content: 'Default'
			}
		}]
	}

};

ctx1 = document.getElementById("RamChartCanvas").getContext("2d");
chrtCanvsRamChart = new Chart(ctx1,
    {
        type: ChartType,
        data: ChartData,
        options: ChartOptions
    });
```

when i use this code, my annotation line is displayed properly, but  javascript is thrown in the console. 

Error : **Uncaught TypeError: Cannot read property 'Annotation' of undefined**

at line : **i.Annotation=i.Annotation||{},**

**Comment by crmaske01** [comment]
Did u get any solution for this? am also facing same issue.

**Comment by lizeidsness** [comment]
I am also having this trouble working integrating this plugin with chart.js under dojo.

**Comment by pxpwoa** [comment]
load chartjs-plugin-annotation.js after chart.js like

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="{% static 'chartjs-plugin-annotation/chartjs-plugin-annotation.js' %}"></script>

**Comment by lizeidsness** [comment]
right - but that isn't using dojo.  That's django.

**Comment by etimberg** [comment]
Quite old and the build system has changed since this was filed
