### ISSUE TITLE
Support borderWidth: 0 for box annotations

### ISSUE THREAD

**Issue by rfunduk** [chartjs/chartjs-plugin-annotation#127]
Hey folks, I am using box annotations to 'mark' areas of a chart (sort of showing down/inactive time periods against other data) and I noticed that specifying `borderWidth` as `0` does not have the intended effect - you always end up with at least a 1px border. At first I tried setting it to transparent or white, but it doesn't look very good.

After a bit of googling it was clear that the issue is `strokeRect` doesn't support 0 `lineWidth` (kind of makes sense? here's a modified codepen from MDN that [demonstrates](https://codepen.io/anon/pen/NzovJw)). So what I think should actually happen is that `strokeRect` should not be called at all if you set `borderWidth: 0` in the settings -- specifically right here: https://github.com/chartjs/chartjs-plugin-annotation/blob/master/src/types/box.js#L139

This is a pretty easy change, obviously, and I have made it on a fork already for my own use. Is this something you would accept as a PR?

**Comment by philippevezina** [comment]
I would need that too, but setting the boderColor to rgba(0, 0, 0, 0) works fine and doesn't show.

**Comment by philippevezina** [comment]
In box.js change this:
`ctx.strokeRect(view.left, view.top, width, height); `
for this:
`if (isNaN(view.borderWidth) || view.borderWidth > 0) { 
      ctx.strokeRect(view.left, view.top, width, height); 
 }`

**Comment by rfunduk** [comment]
Yes as I said I was able to make this change in my own project. This issue is me proposing a PR.

**Comment by flaushi** [comment]
does `border: 0` work?
