### ISSUE TITLE
This annotation not working on ng2-chart

### ISSUE THREAD

**Issue by Jigar3195** [chartjs/chartjs-plugin-annotation#128]
How to use this annotation for ng2-chart?

**Comment by stevendelapena** [comment]
I was able to get this working by adding this to my app.module.ts file:
import 'chartjs-plugin-annotation/src/index.js';

(make sure you've added the npm package for this library as well).

**Comment by snider** [comment]
https://valor-software.com/ng2-charts/#/LineChart there is a demo of how on this page.
