### ISSUE TITLE
Set value of ctx.setLineDash to borderDash option when drawing a box annotation

### ISSUE THREAD

**Issue by albedoa** [chartjs/chartjs-plugin-annotation#133]
The [box annotation type](https://github.com/chartjs/chartjs-plugin-annotation/blob/1643f3c51ffe951c7313ffe1f73a102147626158/src/types/box.js) does not set the value of `ctx.setLineDash` to the `borderDash` option the way that the [line annotation type](https://github.com/chartjs/chartjs-plugin-annotation/blob/1643f3c51ffe951c7313ffe1f73a102147626158/src/types/line.js#L221) does. Is there a reason, or should it be added?

**Comment by etimberg** [comment]
Done in #329
