### ISSUE TITLE
[FEATURE] Add bar border dashed and line by 3 coordinates [x, y, endValue] in dependences of x,y scale

### ISSUE THREAD

**Issue by RieseIch** [chartjs/chartjs-plugin-annotation#134]
I changed code (for myself) for bar and line annotations to add border dashed for bar and additional coordinates for line.

Could you add it to next version?

![image](https://user-images.githubusercontent.com/3750596/46736851-bd730480-cca2-11e8-9bec-c8becf43ede7.png)

`// Box Annotation implementation
module.exports = function(Chart) {
	var helpers = require('../helpers.js')(Chart);
	
	var BoxAnnotation = Chart.Annotation.Element.extend({
		setDataLimits: function() {
			var model = this._model;
			var options = this.options;
			var chartInstance = this.chartInstance;

			var xScale = chartInstance.scales[options.xScaleID];
			var yScale = chartInstance.scales[options.yScaleID];
			var chartArea = chartInstance.chartArea;

			// Set the data range for this annotation
			model.ranges = {};
			
			if (!chartArea) {
				return;
			}
			
			var min = 0;
			var max = 0;
			
			if (xScale) {
				min = helpers.isValid(options.xMin) ? options.xMin : xScale.getPixelForValue(chartArea.left);
				max = helpers.isValid(options.xMax) ? options.xMax : xScale.getPixelForValue(chartArea.right);

				model.ranges[options.xScaleID] = {
					min: Math.min(min, max),
					max: Math.max(min, max)
				};
			}

			if (yScale) {
				min = helpers.isValid(options.yMin) ? options.yMin : yScale.getPixelForValue(chartArea.bottom);
				max = helpers.isValid(options.yMax) ? options.yMax : yScale.getPixelForValue(chartArea.top);

				model.ranges[options.yScaleID] = {
					min: Math.min(min, max),
					max: Math.max(min, max)
				};
			}
		},
		configure: function() {
			var model = this._model;
			var options = this.options;
			var chartInstance = this.chartInstance;

			var xScale = chartInstance.scales[options.xScaleID];
			var yScale = chartInstance.scales[options.yScaleID];
			var chartArea = chartInstance.chartArea;

			// clip annotations to the chart area
			model.clip = {
				x1: chartArea.left,
				x2: chartArea.right,
				y1: chartArea.top,
				y2: chartArea.bottom
			};

			var left = chartArea.left, 
				top = chartArea.top, 
				right = chartArea.right, 
				bottom = chartArea.bottom;

			var min, max;

			if (xScale) {
				min = helpers.isValid(options.xMin) ? xScale.getPixelForValue(options.xMin) : chartArea.left;
				max = helpers.isValid(options.xMax) ? xScale.getPixelForValue(options.xMax) : chartArea.right;
				left = Math.min(min, max);
				right = Math.max(min, max);
			}

			if (yScale) {
				min = helpers.isValid(options.yMin) ? yScale.getPixelForValue(options.yMin) : chartArea.bottom;
				max = helpers.isValid(options.yMax) ? yScale.getPixelForValue(options.yMax) : chartArea.top;
				top = Math.min(min, max);
				bottom = Math.max(min, max);
			}

			// Ensure model has rect coordinates
			model.left = left;
			model.top = top;
			model.right = right;
			model.bottom = bottom;

			// Stylistic options
			model.borderColor = options.borderColor;
			model.borderWidth = options.borderWidth;
			model.backgroundColor = options.backgroundColor;
            model.borderDash = options.borderDash || [];
            model.borderDashOffset = options.borderDashOffset || 0;
		},
		inRange: function(mouseX, mouseY) {
			var model = this._model;
			return model &&
				mouseX >= model.left && 
				mouseX <= model.right && 
				mouseY >= model.top && 
				mouseY <= model.bottom;
		},
		getCenterPoint: function() {
			var model = this._model;
			return {
				x: (model.right + model.left) / 2,
				y: (model.bottom + model.top) / 2
			};
		},
		getWidth: function() {
			var model = this._model;
			return Math.abs(model.right - model.left);
		},
		getHeight: function() {
			var model = this._model;
			return Math.abs(model.bottom - model.top);
		},
		getArea: function() {
			return this.getWidth() * this.getHeight();
		},
        draw: function() {
            var view = this._view;
            var ctx = this.chartInstance.chart.ctx;

            ctx.save();

            // Canvas setup
            ctx.beginPath();
            ctx.rect(view.clip.x1, view.clip.y1, view.clip.x2 - view.clip.x1, view.clip.y2 - view.clip.y1);
            ctx.clip();

            if (ctx.setLineDash) {
                ctx.setLineDash(view.borderDash);
            }
            ctx.lineDashOffset = view.borderDashOffset;

            ctx.lineWidth = view.borderWidth;
            ctx.strokeStyle = view.borderColor;
            ctx.fillStyle = view.backgroundColor;

            // Draw
            var width = view.right - view.left,
                height = view.bottom - view.top;
            ctx.fillRect(view.left, view.top, width, height);
            ctx.strokeRect(view.left, view.top, width, height);

            ctx.restore();
        }
	});

	return BoxAnnotation;
};
`
`// Line Annotation implementation
module.exports = function (Chart) {
    var chartHelpers = Chart.helpers;
    var helpers = require('../helpers.js')(Chart);

    var horizontalKeyword = 'horizontal';
    var verticalKeyword = 'vertical';

    var LineAnnotation = Chart.Annotation.Element.extend({
        setDataLimits: function () {
            var model = this._model;
            var options = this.options;
            var chartInstance = this.chartInstance;

            var xScale = chartInstance.scales[options.xScaleID];
            var yScale = chartInstance.scales[options.yScaleID];

            var chartArea = chartInstance.chartArea;

            // Set the data range for this annotation
            model.ranges = {};

            if (!chartArea) {
                return;
            }

            var min = 0;
            var max = 0;

            if (xScale) {
                min = helpers.isValid(options.x) ? options.x : xScale.getPixelForValue(chartArea.left);
                max = helpers.isValid(options.endValue) ? options.endValue : xScale.getPixelForValue(chartArea.right);

                model.ranges[xScale.id] = {
                    min: Math.min(min, max),
                    max: Math.max(min, max)
                };
            }
            if (yScale) {
                min = helpers.isValid(options.y) ? options.y : yScale.getPixelForValue(chartArea.bottom);
                max = helpers.isValid(options.endValue) ? options.endValue : yScale.getPixelForValue(chartArea.top);

                model.ranges[yScale.id] = {
                    min: Math.min(min, max),
                    max: Math.max(min, max)
                };
            }

        },
        configure: function () {
            var model = this._model;
            var options = this.options;
            var chartInstance = this.chartInstance;
            var ctx = chartInstance.chart.ctx;

            var xScale = chartInstance.scales[options.xScaleID];
            var yScale = chartInstance.scales[options.yScaleID];

            var chartArea = chartInstance.chartArea;
            var x1, y1, x2, y2;

            var max;
            var min;

            if (this.options.mode == horizontalKeyword) {

                if (xScale) {
                    max = helpers.isValid(options.endValue) ? xScale.getPixelForValue(options.endValue) : chartArea.right;
                    min = helpers.isValid(options.x) ? xScale.getPixelForValue(options.x) : chartArea.left;
                } else {
                    max = chartArea.right;
                    min = chartArea.left;
                }

                y1 = y2 = yScale ? (helpers.isValid(options.y) ? yScale.getPixelForValue(options.y) : chartArea.bottom) :
                    chartArea.bottom;

                x1 = Math.min(min, max);
                x2 = Math.max(min, max);

            } else {
                if (yScale) {
                    max = helpers.isValid(options.endValue) ? yScale.getPixelForValue(options.endValue) : chartArea.right;
                    min = helpers.isValid(options.y) ? yScale.getPixelForValue(options.y) : chartArea.bottom;
                } else {
                    max = chartArea.bottom;
                    min = chartArea.bottom;
                }

                x1 = x2 = xScale ? (helpers.isValid(options.x) ? xScale.getPixelForValue(options.x) : chartArea.left) :
                    chartArea.left;

                y1 = Math.min(min, max);
                y2 = Math.max(min, max);
            }

            var chartArea = chartInstance.chartArea;

            // clip annotations to the chart area
            model.clip = {
                x1: chartArea.left,
                x2: chartArea.right,
                y1: chartArea.top,
                y2: chartArea.bottom
            };

            model.x1 = x1;
            model.x2 = x2;
            model.y1 = y1;
            model.y2 = y2;

            model.line = new LineFunction(model);
            model.mode = options.mode;

            // Figure out the label:
            model.labelBackgroundColor = options.label.backgroundColor;
            model.labelFontFamily = options.label.fontFamily;
            model.labelFontSize = options.label.fontSize;
            model.labelFontStyle = options.label.fontStyle;
            model.labelFontColor = options.label.fontColor;
            model.labelXPadding = options.label.xPadding;
            model.labelYPadding = options.label.yPadding;
            model.labelCornerRadius = options.label.cornerRadius;
            model.labelPosition = options.label.position;
            model.labelXAdjust = options.label.xAdjust;
            model.labelYAdjust = options.label.yAdjust;
            model.labelEnabled = options.label.enabled;
            model.labelContent = options.label.content;

            ctx.font = chartHelpers.fontString(model.labelFontSize, model.labelFontStyle, model.labelFontFamily);
            var textWidth = ctx.measureText(model.labelContent).width;
            var textHeight = ctx.measureText('M').width;
            var labelPosition = calculateLabelPosition(model, textWidth, textHeight, model.labelXPadding, model.labelYPadding);
            model.labelX = labelPosition.x - model.labelXPadding;
            model.labelY = labelPosition.y - model.labelYPadding;
            model.labelWidth = textWidth + (2 * model.labelXPadding);
            model.labelHeight = textHeight + (2 * model.labelYPadding);

            model.borderColor = options.borderColor;
            model.borderWidth = options.borderWidth;
            model.borderDash = options.borderDash || [];
            model.borderDashOffset = options.borderDashOffset || 0;
        },
        inRange: function (mouseX, mouseY) {
            var model = this._model;

            return (
                // On the line
                model.line &&
                model.line.intersects(mouseX, mouseY, this.getHeight())
            ) || (
                // On the label
                model.labelEnabled &&
                model.labelContent &&
                mouseX >= model.labelX &&
                mouseX <= model.labelX + model.labelWidth &&
                mouseY >= model.labelY &&
                mouseY <= model.labelY + model.labelHeight
            );
        },
        getCenterPoint: function () {
            return {
                x: (this._model.x2 + this._model.x1) / 2,
                y: (this._model.y2 + this._model.y1) / 2
            };
        },
        getWidth: function () {
            return Math.abs(this._model.right - this._model.left);
        },
        getHeight: function () {
            return this._model.borderWidth || 1;
        },
        getArea: function () {
            return Math.sqrt(Math.pow(this.getWidth(), 2) + Math.pow(this.getHeight(), 2));
        },
        draw: function () {
            var view = this._view;
            var ctx = this.chartInstance.chart.ctx;

            if (!view.clip) {
                return;
            }

            ctx.save();

            // Canvas setup
            ctx.beginPath();
            ctx.rect(view.clip.x1, view.clip.y1, view.clip.x2 - view.clip.x1, view.clip.y2 - view.clip.y1);
            ctx.clip();

            ctx.lineWidth = view.borderWidth;
            ctx.strokeStyle = view.borderColor;

            if (ctx.setLineDash) {
                ctx.setLineDash(view.borderDash);
            }
            ctx.lineDashOffset = view.borderDashOffset;

            // Draw
            ctx.beginPath();
            ctx.moveTo(view.x1, view.y1);
            ctx.lineTo(view.x2, view.y2);
            ctx.stroke();

            if (view.labelEnabled && view.labelContent) {
                ctx.beginPath();
                ctx.rect(view.clip.x1, view.clip.y1, view.clip.x2 - view.clip.x1, view.clip.y2 - view.clip.y1);
                ctx.clip();

                ctx.fillStyle = view.labelBackgroundColor;
                // Draw the tooltip
                chartHelpers.drawRoundedRectangle(
                    ctx,
                    view.labelX, // x
                    view.labelY, // y
                    view.labelWidth, // width
                    view.labelHeight, // height
                    view.labelCornerRadius // radius
                );
                ctx.fill();

                // Draw the text
                ctx.font = chartHelpers.fontString(
                    view.labelFontSize,
                    view.labelFontStyle,
                    view.labelFontFamily
                );
                ctx.fillStyle = view.labelFontColor;
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                ctx.fillText(
                    view.labelContent,
                    view.labelX + (view.labelWidth / 2),
                    view.labelY + (view.labelHeight / 2)
                );
            }

            ctx.restore();
        }
    });

    function LineFunction(view) {
        // Describe the line in slope-intercept form (y = mx + b).
        // Note that the axes are rotated 90° CCW, which causes the
        // x- and y-axes to be swapped.
        var m = (view.x2 - view.x1) / (view.y2 - view.y1);
        var b = view.x1 || 0;

        this.m = m;
        this.b = b;

        this.getX = function (y) {
            // Coordinates are relative to the origin of the canvas
            return m * (y - view.y1) + b;
        };

        this.getY = function (x) {
            return ((x - b) / m) + view.y1;
        };

        this.intersects = function (x, y, epsilon) {
            epsilon = epsilon || 0.001;
            var dy = this.getY(x),
                dx = this.getX(y);
            return (
                (!isFinite(dy) || Math.abs(y - dy) < epsilon) &&
                (!isFinite(dx) || Math.abs(x - dx) < epsilon)
            );
        };
    }

    function calculateLabelPosition(view, width, height, padWidth, padHeight) {
        var line = view.line;
        var ret = {}, xa = 0, ya = 0;

        switch (true) {
            // top align
            case view.mode == verticalKeyword && view.labelPosition == "top":
                ya = padHeight + view.labelYAdjust;
                xa = (width / 2) + view.labelXAdjust;
                ret.y = view.y1 + ya;
                ret.x = (isFinite(line.m) ? line.getX(ret.y) : view.x1) - xa;
                break;

            // bottom align
            case view.mode == verticalKeyword && view.labelPosition == "bottom":
                ya = height + padHeight + view.labelYAdjust;
                xa = (width / 2) + view.labelXAdjust;
                ret.y = view.y2 - ya;
                ret.x = (isFinite(line.m) ? line.getX(ret.y) : view.x1) - xa;
                break;

            // left align
            case view.mode == horizontalKeyword && view.labelPosition == "left":
                xa = padWidth + view.labelXAdjust;
                ya = -(height / 2) + view.labelYAdjust;
                ret.x = view.x1 + xa;
                ret.y = line.getY(ret.x) + ya;
                break;

            // right align
            case view.mode == horizontalKeyword && view.labelPosition == "right":
                xa = width + padWidth + view.labelXAdjust;
                ya = -(height / 2) + view.labelYAdjust;
                ret.x = view.x2 - xa;
                ret.y = line.getY(ret.x) + ya;
                break;

            // center align
            default:
                ret.x = ((view.x1 + view.x2 - width) / 2) + view.labelXAdjust;
                ret.y = ((view.y1 + view.y2 - height) / 2) + view.labelYAdjust;
        }

        return ret;
    }

    return LineAnnotation;
};
`

**Comment by RieseIch** [comment]
function createBarAnnotation(x) {

            var xMax = moment(x).add(1, 'hours').add(40, 'minutes');
            var xMin = moment(x).add(-1, 'hours').add(-40, 'minutes');

            return {
                type: "box",
                id: 'bar_' + x.format("dd_HH"),
                drawTime: "beforeDatasetsDraw",
                xScaleID: "x-axis-0",
                yScaleID: "y-axis-0",
                xMax: xMax,
                xMin: xMin,
                borderColor: "rgb(101, 33, 171)",
                borderWidth: 0.5,
                backgroundColor: "rgba(101, 33, 171, 0)",
                borderDash: [3, 3],

                onMousedown: function (e) {
                    var element = this;
                    element.options.backgroundColor = "rgba(101, 33, 171, 0.2)";
                    chart.update();
                },

                onMouseup: function (e) {
                    var element = this;
                    element.options.backgroundColor = "rgba(101, 33, 171, 0.1)";
                    chart.update();
                },

                onMouseover: function (e) {
                    var element = this;
                    element.options.backgroundColor = "rgba(101, 33, 171, 0.1)";
                    chart.update();
                },
                onMouseleave: function (e) {
                    var element = this;
                    element.options.backgroundColor = "rgba(101, 33, 171, 0)";
                    chart.update();
                },

                onClick: function (e) {
                    console.log("click");
                }
            }
        }

        function createLineAnnotations(x, y) {

            var xMax = moment(x).add(1, 'hours').add(40, 'minutes');
            var xMin = moment(x).add(-1, 'hours').add(-40, 'minutes');

            return {
                type: 'line',
                drawTime: 'afterDatasetsDraw',
                id: 'line_' + x.format("dd_HH_") + y,
                mode: 'horizontal',
                xScaleID: "x-axis-0",
                yScaleID: "y-axis-0",
                x: xMin,
                y: y,
                endValue: xMax,
                borderColor: 'red',
                borderWidth: 1,
                borderDash: [5, 5],
                borderDashOffset: 5,

                label: {
                    backgroundColor: 'rgba(0,0,0,0)',
                    fontFamily: "sans-serif",
                    fontSize: 12,
                    fontStyle: "normal",
                    fontColor: "red",
                    xPadding: 5,
                    yPadding: 0,
                    cornerRadius: 6,
                    position: "right",
                    xAdjust: 0,
                    yAdjust: -10,
                    enabled: true,
                    content: "Max"
                }
            }
        }

**Comment by kurkle** [comment]
These or equivalent have all been implemented in v1.
