### ISSUE TITLE
onMouseleave() stops working if you update chart

### ISSUE THREAD

**Issue by piboistudios** [chartjs/chartjs-plugin-annotation#135]
It appears the onMouseLeave hook for the Line annotation ceases to work if you update the Chart.

I am trying to have an annotation simply increase in size when it's being hovered over, however it seems that after a call to chartInstance.update() the mouseleave events become surpressed.

Code snippet below (this is simply added to the lines annotation in the updates sample):
```
            onMouseleave(evt) {
                console.log("Exited.");
                window.myScatter.options.annotation.annotations[0].borderWidth = 16;
                window.myScatter.update();
            },
            onMouseover(evt) {
                console.log("Entered");
                window.myScatter.options.annotation.annotations[0].borderWidth = 32;
                window.myScatter.options.annotation.annotations[0].borderColor = 'blue';
                evt.preventDefault();
                // window.myScatter.optoins.annotation = 5; <-- this line was originally causing an error (myScatter.optoins = undefined), preventing the update and allowing onMouseleave to fire, once I fixed this error mouseleave stopped firing.
                window.myScatter.update();
            },
```

I logged out the actual annotation instance at the end of onMouseover, and the id is different every time mouseover fires.

It appears that after an update it is creating a new annotation to replace the original, which is probably why onMouseleave never fires.

EDIT: Should also note that after the ID is changed, hovering is still set to true and is never unset.

**Comment by etimberg** [comment]
Working in chart.js v3.0.0-beta.13 and annotation v1.0.0-beta.4 https://jsfiddle.net/v3o4j17g/1/
