### ISSUE TITLE
Vertical annotation with float values do not display

### ISSUE THREAD

**Issue by Evertvdw** [chartjs/chartjs-plugin-annotation#139]
Hello there, 

Made a new instance of issue #79, because that problem does exist. I ran into it to and I did some more investigation. 

Turns out that this is caused by a function in the main repository which is called here:
`pixel = helpers.isValid(options.value) ? scale.getPixelForValue(options.value) : NaN;`

The scale.getPixelForValue implementation has the following code: 				
```
var labels = me.getLabels();
value = valueCategory || value;
var idx = labels.indexOf(value);
index = idx !== -1 ? idx : index;`
```
Which as far as I can see it looks up the value (for instance 4.5) in the array of labels (for instance [1,2,3,4,5]) which of course fails. 

So a solution would be to just do the calculations of the x-coordinate in this case in the plugin itself or get the function fixed in the main repository.

**Comment by chrisadamsonmcri** [comment]
I'm having this problem as well.

**Comment by Evertvdw** [comment]
I figured out what the problem was, it is because I used a categorical scale on which you can only set annotations to something that is a label. 

@chrisadamsonmcri I don't know what your application is but in my case I was making a histogram chart using a bar chart, but I switched to a stepped-line chart to make my histogram.

**Comment by chrisadamsonmcri** [comment]
I am just displaying a line chart with a xAxes with scale = 'linear'
The limits are between 0 and 1 on both axes and I'm trying to draw vertical lines within the plot and its not working.

**Comment by Evertvdw** [comment]
Can you make a fiddle with the code you are using now? Maybe I can help

**Comment by chrisadamsonmcri** [comment]
My bad, I needed to put the annotations in the "options" object. It works now.
