### ISSUE TITLE
onMouseleave and onMouseout not called when mousing onto different annotation

### ISSUE THREAD

**Issue by Techn1x** [chartjs/chartjs-plugin-annotation#140]
I have a lot of annotations on my chart, and I noticed that mouseout/mouseleave events do not occur until ALL annotations are moused away from. Once the mouse leaves all annotations, then all of the mouseout/mouseleave events occur immediately

**Comment by Techn1x** [comment]
The cause is this code here https://github.com/chartjs/chartjs-plugin-annotation/blob/master/src/events.js#L49-L64 which only causes the hover-off code to trigger when zero elements are found at the cursor location (i.e. `if (!element)...`)

The solution is to remember the last hovered element, then trigger the hover-off logic for it, when a new element is hovered (i.e. the code above what I linked)

Working on a PR for it now

**Comment by vemuez** [comment]
Yup, I'm having this exact same issue. An example of this: https://jsfiddle.net/cb84xonk/
I've increased the vertical padding to ensure some overlap happens to get the idea across. 

You'll notice if you move back and forth between the same annotations, the triggers do not re-invoke but resets after you leave the annotations as a whole

**Comment by kurkle** [comment]
This was fixed in #239
