### ISSUE TITLE
padding issue with drawing an average line

### ISSUE THREAD

**Issue by cohenu** [chartjs/chartjs-plugin-annotation#146]
Hey All,
I know that I can use the following:

```js
layout: {
  padding: {
    left: 0,
    right: 30,
    top: 0,
    bottom: 0
  }
},
```

to create padding from the right side, when I do that and draw an average line with annotation plugin  the average line gets also the padding. Is there a way to draw the line on 100% width of the canvas and the chart will ends 30px from the right side?

**Comment by stockiNail** [comment]
@cohenu I think this issue is already solved from version [1.0.2](https://github.com/chartjs/chartjs-plugin-annotation/releases/tag/v1.0.2)

See codepen: https://codepen.io/stockinail/pen/abyrGav
