### ISSUE TITLE
Can I change z-index property of the labels?

### ISSUE THREAD

**Issue by cohenu** [chartjs/chartjs-plugin-annotation#147]
Hey all,
I have multiple average lines on the chart and when they are close to each other I want the labels on top of the lines not behind them. is there an option to control this behavior ?

**Comment by cohenu** [comment]
example of the problem I'm trying to solve : https://i.imgur.com/cejmWE9.png

**Comment by AmlisPanda** [comment]
Same !

**Comment by joshkel** [comment]
This looks like a duplicate of #94; see #161.

**Comment by etimberg** [comment]
Closing as duplicate
