### ISSUE TITLE
Chart js Annotation label cuts off when positioned to the right

### ISSUE THREAD

**Issue by sdaniel1609** [chartjs/chartjs-plugin-annotation#151]
The chart js annotation label seems to cut off the canvas when aligned to the right side of the chart. 
I tried adding Padding but that does not seem to work. 

Here is what i mean:
![image](https://user-images.githubusercontent.com/30237907/52217847-38cf7600-2891-11e9-8235-e502347154db.png)

Are there any configurations I can use to align the label on the right side without cutting off text?

Here is my annotation configs:

`
                label: {
                  backgroundColor: 'rgba(0,0,0,0)',
                  enabled: true,
                  content: 'Avg',
                  position: 'right',
                  xAdjust: -15,
`
Thanks!

**Comment by chrisokamoto** [comment]
I have the same problem.. did you manage to create a workaround for this?

**Comment by chrisokamoto** [comment]
Well, in my case.. I had a vertical line with annotation, and when the line was plot in the extreme rigth edge of the graph, then I had this problem of the annotation tag being cutted. The workaround that solved this for me, although a bit hacky, was to set a small endValue for the annotation:

`annotation: {

       annotations: [
          {
            type: "line",
            mode: "vertical",
            scaleID: "x-axis-0",
            value: getProjectTargetSize(),
            endValue: parseInt(getProjectTargetSize()) + 10,
            borderColor: "red",
            label: {
              content: "TAR",
              enabled: true,
              position: "bottom",
              xAdjust: -17
            }
          },`

**Comment by tobiasbueschel** [comment]
Hi @sdaniel1609 & @chrisokamoto 👋,

I ran into the same issue and "solved it" (in a hacky way) by offsetting the label using `xAdjust`  depending on whether it was the first or last element in the column. 

Here is a JsFiddle that explains what I mean: https://jsfiddle.net/Lq473vx9/

Would be great if this plugin would handle such situations! @etimberg what do you think?

**Comment by Githamza** [comment]
Looking for a solution also, if it's possible to put the label z-index > to graph

**Comment by rashearth** [comment]
HI, is this problem still not solved?
i also have the same issue.
in my case, i want to overlap the label on top of the axis.

but i found that the datalabel plugin have been worked succesfully on overlaying labels on top of any chart.
it would be great if we could find solutions from this hint.
https://chartjs-plugin-datalabels.netlify.com/samples/scriptable/data.html

<img width="105" alt="スクリーンショット 2019-08-31 14 00 43" src="https://user-images.githubusercontent.com/26535295/64059457-05bb4e00-cbf8-11e9-8a1f-07873c983725.png">

**Comment by mikpetr** [comment]
Same issue for me, but for me it appears when I use custom font. When I make a hard reload and font is not loaded yet it cut the right side. When I refresh again the problem gone.

**Comment by eschao** [comment]
Same problem, can we make the label is over the axis? Sometimes we actually want to the label is same x position with the number on Y axis, just like one of them, but with different font style and color.
Hope to support it!

**Comment by hacksdump** [comment]
I tried changing the offsets programmatically. Hope it helps.
[gist](https://gist.github.com/hacksdump/92315ae80cb0671c4c8bc896c72dd188

**Comment by kurkle** [comment]
No repro with v1: https://codepen.io/kurkle/pen/WNRLWOM?editors=1010
