### ISSUE TITLE
Issue with Line Annotations

### ISSUE THREAD

**Issue by jamezamm** [chartjs/chartjs-plugin-annotation#154]
When a part of a box annotation is out of visible range of the chart, part of the box will be hidden. (Which is correct). The same could not be said for the line annotations. 

Using the same example provided in Github (Copy/Paste), please find below some test cases.

**Test Case 1: Box Annotation** 

Box Configuration: yMin = 80, yMax = 200
Expected Behavior: 80 - 100 is visible while 100 - 200 is hidden
Actual Behavior: 80 - 100 is visible while 100 - 200 is hidden (Correct)

![image](https://user-images.githubusercontent.com/1955189/53548876-f537f700-3b32-11e9-99ef-3a03bc61a4c5.png)
 
**Test Case 2: Line Annotation** 

Line Configuration: Value = 500
Expected Behavior: The line should be hidden
Actual Behaviour: The chart generates ticks to 500 till the line is visible (Incorrect)

![image](https://user-images.githubusercontent.com/1955189/53548931-26182c00-3b33-11e9-80ce-667f095bae3e.png)

Any ideas?

**Comment by kurkle** [comment]
Current behavior is to expand the scale ranges so annotations are visible, unless the scale ranges have been explicitly defined.

**Comment by kurkle** [comment]
Resolved by #419
