### ISSUE TITLE
Allow a fixed width in box annotation

### ISSUE THREAD

**Issue by kmexnx** [chartjs/chartjs-plugin-annotation#155]
I think a good enhancement would be a fixed width for the box annotation 

just add 
`var fixedWitdh = this.options.fixedWith ? this.options.fixedWith : undefined;`

and if `fixedWitdh` exists 

`var width = fixedWith ? fixedWith : view.right - view.left` at line 137 box.js file

**Comment by etimberg** [comment]
I don't this makes sense to do as it wouldn't position the box well.
