### ISSUE TITLE
Labels not displayed when (x/y)Adjust not set for line annotation

### ISSUE THREAD

**Issue by dimhoff** [chartjs/chartjs-plugin-annotation#162]
When there is no xAdjust or yAdjust set on for the label of a line annotation no labels will show up. I expected that if these options aren't set a default of '0' would be used.

The problem seems to be that in src/types/line.js the calculateLabelPosition() function tries to calculate the label positions using the values of xAdjust/yAdjust. This leads to NaN instead of a valid position.

Haven't looked to much at the code but a possible solution might be to changes lines 153 & 154 of line.js as follows:

`
model.labelXAdjust = options.label.xAdjust ? options.label.xAdjust : 0;
model.labelYAdjust = options.label.yAdjust ? options.label.yAdjust : 0;`

**Comment by etimberg** [comment]
Defaults of `0` appear to be added now
