### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by gj1118** [chartjs/chartjs-plugin-annotation#165]
Hi, 
I was wondering if there is way to set the background-color as a gradient of the box annotation instead of a solid color ?  

Can you please confirm ?

Thanks
Gagan

**Comment by bingo4508** [comment]
@gj1118 Yes, it's possible. Please check https://github.com/chartjs/Chart.js/blob/0d01bcf5cca3a85c97305ad44925113cdead9c74/docs/general/colors.md#patterns-and-gradients
