### ISSUE TITLE
adding data or colored number on top of the axis. 

### ISSUE THREAD

**Issue by rashearth** [chartjs/chartjs-plugin-annotation#169]
Hi,
i have one simple feature for chart.js annotation .
Heres the detailed information.
I just created this issue in the chart.js github issue as well
https://github.com/chartjs/Chart.js/issues/6397

      <What I want to do>
I want to highlight or plot colored axis data as the picture below.
<img width="113" alt="59426888-4a62f480-8e14-11e9-8ea9-6ca5c9257acc (1)" src="https://user-images.githubusercontent.com/26535295/61587602-2be8d980-abc8-11e9-9712-8c07078ebd66.png">

      < what i tried > 
I tried to work it out by changing paddings, but none of it worked.

Im not sure it could work in the previous chat.js version, but please let us know if there is any way to overide data or number on the axis.
if there is no function for previous version, It would be great if you could add this function.

Thank you & Regards,
Rashearth

**Comment by benmccann** [comment]
You'd have to draw a box using the canvas API. You can see how the labels are drawn here: https://github.com/chartjs/Chart.js/blob/626d8cc7140a3ccd9efdd692ff12dcaadaf465c1/src/core/core.scale.js#L1150

**Comment by rashearth** [comment]
thx @benmccann
let me hire some people in upwork and give a try for making a plugin

**Comment by kurkle** [comment]
This is already doable: https://codepen.io/kurkle/pen/zYNyXqe
