### ISSUE TITLE
Line height [feature request]

### ISSUE THREAD

**Issue by Seabizkit** [chartjs/chartjs-plugin-annotation#171]
hi please add and option to specify that the line should only go to the height of the value instead of all the way to the top

**Comment by projectcalix** [comment]
+ second this

**Comment by kurkle** [comment]
You can specify this today.
 
Following annotation config (only the relevant keys noted) would draw a vertical line at x:0 from y:10 to y:20.
```js
{
  type: 'line',
  xMin: 0,
  xMax: 0,
  yMin: 10,
  yMax: 20
}
