### ISSUE TITLE
The box begins from middle of the grid section

### ISSUE THREAD

**Issue by curiousPup** [chartjs/chartjs-plugin-annotation#172]
In the example documented here, the box annotation draws the box beginning from the start of the section, but when I implemented, it begins from the middle.

I'm plugging this in with react-chartjs. Is there anything to fix the issue?

![image](https://user-images.githubusercontent.com/10569518/62867702-90afd380-bd31-11e9-93c4-2c5a8af626e6.png)
![image](https://user-images.githubusercontent.com/10569518/62867747-a02f1c80-bd31-11e9-85e8-bdb2a603e26d.png)

**Comment by curiousPup** [comment]
Apparently, the issue occurs when you have more than two datasets

**Comment by jkosonen** [comment]
it works with chart.js 2.5, but not with 2.8

**Comment by kurkle** [comment]
That happens with category scale. You can use fractional index values to go between labels (tested with Chart.js 2.9.4 and annotation 0.5.7). 
For example, `xMin: 1.5` would be half way between 2nd and 3rd label.
