### ISSUE TITLE
Event works outside annotation

### ISSUE THREAD

**Issue by ZsharE** [chartjs/chartjs-plugin-annotation#176]
I can handle click events outside annotation, everywhere in the red rectangle.
It should work only inside the annotation.

![image](https://user-images.githubusercontent.com/3825743/63176026-d4664e00-c04d-11e9-97e7-78b63192212d.png)

Demo here: https://jsfiddle.net/ZsharE/8nec704L/

**Comment by etimberg** [comment]
Handlers have been re-written since this was filed so this likely does not occur anymore
