### ISSUE TITLE
[bug] mouseover and mouseout events doesn't work from Chart.js-2.7.0

### ISSUE THREAD

**Issue by shmoon-kr** [chartjs/chartjs-plugin-annotation#179]
I found that mouseover event and mouseout event doesn't work with the current version of Chart.js.

The error message is 'Unable to preventDefault inside passive event listener invocation'
You can easily test it using horizontal line annotation example in the project.
chartjs-plugin-annotation/samples/horizontal-line.html

I tested for various versions of Chart.js and found that it doesn't work from 2.7.0

--

**Comment by spotnape** [comment]
I seem to have this problem too.

**Comment by neorganic** [comment]
Use char.js 2.5.0

**Comment by spotnape** [comment]
I tried switching back to 2.5.0 and unfortunately the config I have for the rest of the chart stops working. 😞

**Comment by tkyeow** [comment]
Add unique "id" to each annotation element fixed the problem for me

Look at this sample https://jsfiddle.net/beaver71/3qkcLk6v/, which is using 2.7

**Comment by Ribeiro-Tiago** [comment]
Adding a unique id didn't work for me, with versions chart.js v2.9.3 and chartjs-plugin-annotation v0.5.7
