### ISSUE TITLE
if box annotation has yMax not specified, then undefined errors is being thrown 

### ISSUE THREAD

**Issue by mkantautas** [chartjs/chartjs-plugin-annotation#180]
Chart.js 2.5.0
chartjs-plugin-annotation 0.5.5

if box annotation has yMax not specified, then undefined errors are being thrown even though the docs say that should be an issue. 

>Box Annotations
>Box annotations are supported. If one of the axes is not specified, the box will take the entire chart dimension.
>The 4 coordinates, xMin, xMax, yMin, yMax are optional. If not specified, the box is expanded out to the edges

Because I want the yMax to go the end of the graph

**Comment by mattdaviscodes** [comment]
Still a problem.

**Comment by etimberg** [comment]
Duplicate of #136
