### ISSUE TITLE
Move line in bar chart on the left of bar, not on but between bars in grouping

### ISSUE THREAD

**Issue by hstemplewski** [chartjs/chartjs-plugin-annotation#187]
Hi i'd like to draw annotation (line) in bar chart. Not on value but on the left of my grouping bars
Can someone help me with it ?

<img width="1017" alt="Issue annotation" src="https://user-images.githubusercontent.com/25898331/66383413-3b084800-e9bd-11e9-969a-268a688b6443.png">

**Comment by lilooeval** [comment]
HI
I get the same issue, any visibility on enhancement availability date ? Thanks

**Comment by kurkle** [comment]
https://www.chartjs.org/chartjs-plugin-annotation/samples/charts/bar.html
