### ISSUE TITLE
Trendline not appearing

### ISSUE THREAD

**Issue by BobDunkeroo** [chartjs/chartjs-plugin-annotation#190]
Hi, I am probably just not using the plugin correctly but my trendline is not appearing on my dataset.
Does anybody know why?

`var Chart = new Chart(ctx, {

    type: 'scatter',

    data: {
        datasets: [{
            data: [{x: 1000, y: 200}, {x: 800, y: 190}, {x: 1343, ny: 237}, {x: 1689, y: 342}, 
                   {x: 2583, y: 537}, {x: 1733, y: 375}, {x: 2349, y: 598}, {x: 1724, y: 460}, 
                   {x: 1965, y: 487}, {x: 1278, y: 289}, {x: 738, y: 137}
                  ],
            pointBorderColor: 'rgb(255,223,0)',
            borderColor: 'rgb(255,223,0)',
        }],
        
    },
    options: {
        title:{
            display: true,
            text: 'Square Feet vs Housing Price',
            fontSize: 24
        },
        legend:{
            display: false
        },
        scales:{
            yAxes:[{
                scaleLabel: {
                    display: true,
                    labelString: 'Price (thousand)',
                    fontSize: 18
                },
            }],
            xAxes:[{
                scaleLabel: {
                    display: true,
                    labelString: 'Square Feet',
                    fontSize: 18,
                    type: 'linear',
                    position: 'bottom'
                },
            }],
        },
        tooltips: {
            mode: 'index',
            intersect: true
        },
        annotation: {
            annotations: [{
              type: 'line',
              mode: 'horizontal',
              scaleID: 'y-axis-0',
              value: 2225,
              endValue: 0,
              borderColor: 'rgb(75, 192, 192)',
              borderWidth: 4,
              label: {
                enabled: true,
                content: 'Trendline',
                yAdjust: -16,
              }
            }]
        }
    }
});`

**Comment by asehdev** [comment]
You need to register the plugin first to use that. Please check here: https://github.com/chartjs/chartjs-plugin-annotation/issues/156
I think this will solve your query!
