### ISSUE TITLE
Security vulnerability (moment-2.13.0.min.js)

### ISSUE THREAD

**Issue by zhonglin94** [chartjs/chartjs-plugin-annotation#194]
I observed that this plugin depends on a library named moment-2.13.0.min.js which has a critical security vulnerability. 

The main reason is that the latest version of chartjs-plugin-annotation depends on chart.js 2.4.0 and this version of chartjs depends on moment-2.13.0.min.js. So chartjs-plugin-annotation includes a critical issue of security vulnerability.

**Comment by ShineSmile** [comment]
https://github.com/chartjs/chartjs-plugin-annotation/pull/196

**Comment by kurkle** [comment]
There is no moment dependency anymore
