### ISSUE TITLE
Array of label contents does not display them on a new line

### ISSUE THREAD

**Issue by nico-bohlinger** [chartjs/chartjs-plugin-annotation#199]
This will display text1,text2 in one line.
`label: {
                            content: ['text1', 'text2'],
                            enabled: true,
                            position: "top"
}`

I'm not sure if that is the wanted behaviour but the readme states:
`// Text to display in label - default is null. Provide an array to display values on a new line`

So the above code snippet should generate both strings among each other and not in one line

**Comment by rohanpruthi** [comment]
+1
-------------------------------------------------------

- chart.js: 2.9.3,
- chartjs-plugin-annotation: 0.5.7
- web broweser: Google Chrome 79.0.3945.130

**Comment by JonasMH** [comment]
The feature is relatively new and the package haven't been updated on npm in a while. Meanwhile you can always point directly to the repository to enable the feature in your package.json:
`"chartjs-plugin-annotation": "chartjs/chartjs-plugin-annotation#master"`

**Comment by hhsievertsen** [comment]
+1

**Comment by ekersale** [comment]
@JonasMH the bug is still there even with the github master version.

**Comment by netocervantes98** [comment]
+1

**Comment by adrienne** [comment]
+1

**Comment by Nsrose** [comment]
Was this ever resolved? Any workarounds?

**Comment by kurkle** [comment]
This works in 1.0.0-rc

```js
content: (ctx) => ['Upper bound: ', maxValue(ctx).toFixed(3)],
```

![image](https://user-images.githubusercontent.com/27971921/114756214-2e5b7180-9d63-11eb-96ac-0dd9d7dcf787.png)

https://www.chartjs.org/chartjs-plugin-annotation/samples/types/line.html
