### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by thibauds** [chartjs/chartjs-plugin-annotation#2]
It would be nice to be able to install it via `bower`.
It is suggested in the `readme` but there is no `bower.json`

**Comment by etimberg** [comment]
@thibauds good call to put it in the readme. I think the best way to install this would be to use the npm-resolver for bower: https://github.com/mjeanroy/bower-npm-resolver

**Comment by thibauds** [comment]
@etimberg Thank you for the tip !

**Comment by thibauds** [comment]
@etimberg would you accept a PR if I add a bower.json ?
