### ISSUE TITLE
trouble importing chartjs-plugin-annotation on React

### ISSUE THREAD

**Issue by Jcct100** [chartjs/chartjs-plugin-annotation#208]
Hi there, 

I am having trouble importing chartjs-plugin-annotation. I am getting this error "could not find a declaration file for module 'chartjs-plugin annotation"

When I console.log chart plugin i could see annotation but I can't import it 
<img width="241" alt="Screenshot 2020-02-25 at 00 09 02" src="https://user-images.githubusercontent.com/24507356/75202474-43da9a00-5763-11ea-9994-bda9b3697eba.png">

Any help would be very much appreciated! Thank you!

**Comment by danmana** [comment]
That looks like it's just a warning that there is no typescript definition for the module.
You should still be able to use it without problems, as `any`.

I'm working on writing a ts definition for this plugin ... once it's published you should be able to fix the warning by running
`npm install --save-dev @types/chartjs-plugin-annotation`
