### ISSUE TITLE
Line don't appear 

### ISSUE THREAD

**Issue by MGMehdi** [chartjs/chartjs-plugin-annotation#209]
Hi,
I already read other issue but without succes
I use ReactJs, I make the npm install and here is my code

```
let chart = new Chart(myChartRef, {
                type: "line",
                data: {
                    labels: date,
                    datasets: [{ label: measure, data: quality, borderColor: "blue", showLine: true, pointRadius: 10, pointHoverRadius: 15 }]
                },
                options: {
                    events: ['click'],
                    responsive: true,
                    scales: {
                        xAxes: [{
                            type: 'time',
                            distribution: 'series'
                        }]
                    },
                    tooltips: {
                        mode: "index",
                        intersect: true
                    },
                    plugins: {
                        annotation: {
                            annotations: [{
                                type: 'line',
                                mode: 'horizontal',
                                scaleID: 'y-axis-0',
                                value: 62,
                                borderColor: 'rgb(255, 192, 192)',
                                borderWidth: 4,
                            }]
                        }
                    }
                }
            });
```
And it's in the console

![image](https://user-images.githubusercontent.com/48625769/76774546-55ccbd00-67a4-11ea-98d6-94f256115f25.png)

**Comment by cirmaciu** [comment]
Try to put your annotation settings right under options, Like this: https://codepen.io/jordanwillis/pen/qrXJLW
Somehow it doesn't work with `options.plugins.annotation`

**Comment by AlexanderRodecape** [comment]
I couldn't get any line to appear either, until I added the annotation element as a child of options.
 options: {
                annotation: {
                    annotations: [
                        {
                            type: 'line',
                            mode: 'vertical',
                            scaleID: 'x-axis-0',
                            value: payday.toString(),
                            borderColor: 'red',
                            borderWidth: 2,
                        }
                    ]
                }
            }

**Comment by lilouch** [comment]
Lines don't appear with scatter type of ChartJS. It works well with line type but when I'm doing the same for scatter type, it does not work. Any clues on that ?
Thank

**Comment by varunwilson6** [comment]
Mee too having the same, 
 <Line
            width={200}
            height={300}
            data = {{
              labels: labels,
              datasets: [{
                 label: 'Voltage Fluctuation',
                 data: data,
                 borderWidth: 1
              }]
           }}
            options={{
              maintainAspectRatio: false, 
              legend: { display: false },
              scales: {
                xAxes: [{
                   type: 'time',
                   time: {
                      unit: 'minute',
                      displayFormats: {
                         hour: 'HH:mm:ss'
                      }
                   }
                }]
             },
             annotation: {
              annotations: [{
                type: 'line',
                mode: 'horizontal',
                scaleID: 'y-axis-0',
                value: 233,
                borderColor: 'rgb(75, 192, 192)',
                borderWidth: 4,
                label: {
                  enabled: false,
                  content: 'Test label'
                }
              }]
            }
            }}
          />
