### ISSUE TITLE
Getting annotation events to fire before Chart events

### ISSUE THREAD

**Issue by chrisadamsonmcri** [chartjs/chartjs-plugin-annotation#212]
I'm using a double click event for my chart and my annotation objects. The Chart event is fired first. However, I want the annotation event to be fired first. Any ideas on how I can do that?

**Comment by kurkle** [comment]
Chart does not have a double click event, so it fires 2 click events instead. The double click event is fired before the 2nd click.

You could add similar code that this lib has to your chart click handler, to detect double clicks.

Second option would be to request/add double click handling in core Chart.js.

I don't think there is anything that can be done in this plugin for this, so I'm closing the issue.
