### ISSUE TITLE
rotation is not working

### ISSUE THREAD

**Issue by kalthwaini** [chartjs/chartjs-plugin-annotation#215]
im using chartjs v 2.8, and the option rotation:90 is not working with me.

**Comment by tech-no-crat** [comment]
Experiencing the same issue.

**Comment by tech-no-crat** [comment]
Here's a codepen illustrating the issue: https://codepen.io/tech-no-crat/pen/NWGMZNy

**Comment by dsmackie** [comment]
> Here's a codepen illustrating the issue: https://codepen.io/tech-no-crat/pen/NWGMZNy

You are using v0.5.5 in your sample. Rotation has only been added to the master branch and is not yet available from a cdn.

You will need to compile the plugin yourself.

**Comment by wdavies973** [comment]
@kalthwaini @tech-no-crat If you're looking for the quick way to do this, use the Github "download as zip" on the master branch of the plugin. Then, extract and unzip the folder into your project folder. Then all you have to do is run ```npm install ./chartjs-plugin-annotation-master``` from your project folder, then delete the folder.

**Comment by Veda-cmd** [comment]
Add the following in package.json
"chartjs-plugin-annotation": "git://github.com:chartjs/chartjs-plugin-annotation.git#master"

**Comment by TokerX** [comment]
Rotation still doesn't work for me, even with the master branch installed. :/ Does it depend on other settings?

**Comment by Veda-cmd** [comment]
Its working for me by installing the master branch. It does not depend on other settings.
{
    rotation: -90
}
This is the only line I have added for rotation.

**Comment by TokerX** [comment]
Could it be the version of chart.js? I'm running 2.9.3, OP's running 2.8.
Here's the code:
`					{
						type: 'line',
						mode: 'vertical',
						scaleID: 'x-axis-0',
						value: "21/07/2020",
						borderColor: '#16a085',
						borderWidth: 2,
						label: {
							enabled: true,
							content: 'TEST',
							backgroundColor: 'rgba(255,255,255,0.5)',
							fontColor: "#1abc9c",
							fontFamily: "Roboto",
							rotation: 90
						}
					}`
Any known conflicts with jQuery maybe? Although I'm getting no errors.

**Comment by Veda-cmd** [comment]
"chartjs-plugin-annotation": {
      "version": "git://github.com/chartjs/chartjs-plugin-annotation.git#53630421b5d2e5d6790de3d32c1fb7d3cdc590e2",
      "from": "git://github.com/chartjs/chartjs-plugin-annotation.git#master"
    }
This is the version in my package-lock.json. Are you sure you installed it through git?
Also do not write the annotation property inside plugins. Keep it outside plugins like below.
chartOptions = {
          annotation: {
			annotations: [{
				drawTime: 'afterDraw', // overrides annotation.drawTime if set
				id: 'a-line-1', // optional
				type: 'line',
				mode: 'horizontal',
				scaleID: 'y-axis-0',
				value: '25',
				borderColor: 'red',
				borderWidth: 2
			}]
		}
}

**Comment by TokerX** [comment]
Yes, I have installed it through git, I've also done it manually like wdavies973 suggested. Putting the annotation outside also doesn't make a difference. Oh well, it's not that important anyway, just aesthetics. :)

**Comment by Veda-cmd** [comment]
@TokerX please share the snippet from your package-lock.json for this.

**Comment by JGeraldoLima** [comment]
I can confirm that @Veda-cmd solution works (at least by now)   :)

**Comment by wsuszycki** [comment]
File "chartjs-plugin-annotation.js" from master branch doesn't contain code responsible for rotation. But file "src/types/line.js" has it. I attach fixed file. Works fine. I tried different rotations: 0, 90, 270.
[chartjs-plugin-annotation-rotation.zip](https://github.com/chartjs/chartjs-plugin-annotation/files/4988167/chartjs-plugin-annotation-rotation.zip)

**Comment by Veda-cmd** [comment]
@JGeraldoLima yes it is a temporary fix for now. 

@wsuszycki I had installed from master branch in my project and it was working fine. I have shared package-lock.json snippet from above.
