### ISSUE TITLE
No release in 3 years?

### ISSUE THREAD

**Issue by zacharyfox** [chartjs/chartjs-plugin-annotation#216]
Can we can a release? There are fixed issues that are affecting me that would be nice to not have to workaround.

**Comment by mill1000** [comment]
Second this. The versions available on common CDNs are not usable.

I put together a "v0.5.8" build in my fork and it can be accessed via jsDelivr here:
https://cdn.jsdelivr.net/gh/mill1000/chartjs-plugin-annotation@v0.5.8/chartjs-plugin-annotation.min.js

Or if anyone doesn't trust me, fork it yourself and use your CDN of choice.

**Comment by MikeBishop** [comment]
Would be nice to have an npm release we could pull from as well, though.

**Comment by david0673** [comment]
meanwhile, you could also install from a specific commit hash, e.g. place this in your package.json:
`"chartjs-plugin-annotation": "git+https://github.com/chartjs/chartjs-plugin-annotation#53630421b5d2e5d6790de3d32c1fb7d3cdc590e2"`

**Comment by MikeBishop** [comment]
Good suggestion -- I didn't know you could do that!  Oddly enough, my project that currently uses @mill1000's package loses its annotation when I put that in, do `npm install`, and point to the local file.  It seems to be pulling the most up-to-date code (it has the line changed by the most recent commit) and the browser is loading it.

I'm not going to debug further right now, but I'll try to figure out why later.

**Comment by stockiNail** [comment]
I see that @kurkle is working and doing an amazing work porting the plugin to Chart.js version 3.
@kurkle ur awesome

**Comment by kurkle** [comment]
v1.0.0-beta published today (for chart.js v3-beta.7)

**Comment by paulhayessilex** [comment]
great, would be amazing to have an example using chart.js v3-beta.7 - it's so hard to get working

**Comment by paulhayessilex** [comment]
@kurkle any chance of a React example???

**Comment by kurkle** [comment]
https://codesandbox.io/s/condescending-swirles-3swdb

**Comment by paulhayessilex** [comment]
> https://codesandbox.io/s/condescending-swirles-3swdb

THANK YOU SO MUCH!!!!

**Comment by paulhayessilex** [comment]
Any chance you know how to get the typescript not to complain that annotations isn't a valid property of plugins?

**Comment by paulhayessilex** [comment]
> Any chance you know how to get the typescript not to complain that annotations isn't a valid property of plugins?

Maybe this...
```
export type ChartOptionsWithPlugins = ChartOptions & {
  plugins: {
    [key: string]: Record<string, unknown>
  }
}
```

**Comment by paulhayessilex** [comment]
I'm still getting an error though
````
TypeError: Cannot read property 'prototype' of undefined
    at TypedRegistry.isForType (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:4943:72)
    at Registry._getRegistryForType (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5080:12)
    at C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5060:36
    at Array.forEach (<anonymous>)
    at Registry._each (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5059:13)
    at Registry.add (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5016:8)
    at Function.Chart.register (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:6077:11)
    at Module../src/presentational/chart/Chart.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:4095:50)
    at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
    at Module../src/presentational/widgets/PricesGraph/PriceGraph.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:7524:70)
    at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
    at Module../src/views/Widgets/PricesGraphView/PricesGraphView.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:9314:104)
    at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
    at Module../src/views/Pages/StructuredProductDetailsView/StructuredProductDetailsView.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:8692:98)
    at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
    at Module../src/pages/products/structured/[pid].tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:4008:128)
````

**Comment by paulhayessilex** [comment]
It's weird because if I navigate to the page directly, it breaks, but if I load a different page and then navigate to the page with that graph, it works. Seems to me my import order is wrong, but I'm sure it's correct

**Comment by paulhayessilex** [comment]
```
import React, { useEffect, useRef, useCallback } from 'react'

import {
  Chart as Chartjs,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  Title,
  CategoryScale,
  Tooltip,
  TimeScale,
} from 'chart.js'
import 'chartjs-adapter-moment'
import { Annotation } from 'chartjs-plugin-annotation'

import type {
  ChartOptions,
  ChartData,
  ChartType,
  Plugin,
  UpdateMode,
  DefaultDataPoint,
} from 'chart.js'

import { noop } from '../../utils/noop'

export type ChartOptionsWithPlugins = ChartOptions & {
  plugins: {
    [key: string]: Record<string, unknown>
  }
}

export interface IChartProps {
  chartId: string
  data: ChartData
  options: ChartOptions | ChartOptionsWithPlugins
  type: ChartType
  updateMode?: UpdateMode
  plugins?: Plugin[]
}

export const Chart = ({ data, options, type, plugins, updateMode, chartId }: IChartProps) => {
  const chartInstance = useRef<Chartjs<ChartType, DefaultDataPoint<ChartType>, unknown>>({
    update: noop,
    destroy: noop,
  } as Chartjs)

  useEffect(() => {
    chartInstance.current.options = options
    chartInstance.current.data = data

    chartInstance.current.update(updateMode)
  }, [data, options])

  const nodeRef = useCallback<(instance: HTMLCanvasElement | null) => void>((node) => {
    chartInstance.current.destroy()

    if (node) {
      chartInstance.current = new Chartjs(node, {
        type,
        data,
        options,
        plugins,
      })
    }
  }, [])

  return <canvas ref={nodeRef} id={chartId} />
}

Chartjs.register = Chartjs.register || noop

Chartjs.register(
  Tooltip,
  CategoryScale,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  TimeScale,
  Title,
  Annotation
)
```

**Comment by kurkle** [comment]
> I'm still getting an error though
> 
> ```
> TypeError: Cannot read property 'prototype' of undefined
>     at TypedRegistry.isForType (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:4943:72)
>     at Registry._getRegistryForType (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5080:12)
>     at C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5060:36
>     at Array.forEach (<anonymous>)
>     at Registry._each (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5059:13)
>     at Registry.add (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:5016:8)
>     at Function.Chart.register (C:\Users\phayes\repositories\sparkweb\node_modules\chart.js\dist\chart.js:6077:11)
>     at Module../src/presentational/chart/Chart.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:4095:50)
>     at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
>     at Module../src/presentational/widgets/PricesGraph/PriceGraph.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:7524:70)
>     at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
>     at Module../src/views/Widgets/PricesGraphView/PricesGraphView.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:9314:104)
>     at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
>     at Module../src/views/Pages/StructuredProductDetailsView/StructuredProductDetailsView.tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:8692:98)
>     at __webpack_require__ (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:23:31)
>     at Module../src/pages/products/structured/[pid].tsx (C:\Users\phayes\repositories\sparkweb\.next\server\pages\products\structured\[pid].js:4008:128)
> ```

What I read from that: 
One of the parameters supplied to `Chart.register` is undefined (at Module../src/presentational/chart/Chart.tsx)

**Comment by paulhayessilex** [comment]
yeah, but if I comment out Annotation, it works fine

**Comment by paulhayessilex** [comment]
Ok, so if anyone has this issue, the fix is to place to register the plugins after React has created the ref...

```
import React, { useEffect, useRef, useCallback } from 'react'

import type {
  ChartOptions,
  ChartData,
  ChartType,
  Plugin,
  UpdateMode,
  DefaultDataPoint,
} from 'chart.js'
import {
  Chart as Chartjs,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  Title,
  CategoryScale,
  Tooltip,
  TimeScale,
} from 'chart.js'
import 'chartjs-adapter-moment'
import { Annotation } from 'chartjs-plugin-annotation'

import { noop } from '../../utils/noop'

export type ChartOptionsWithPlugins = ChartOptions & {
  plugins: {
    [key: string]: Record<string, unknown>
  }
}

export interface IChartProps {
  chartId: string
  data: ChartData
  options: ChartOptions | ChartOptionsWithPlugins
  type: ChartType
  updateMode?: UpdateMode
  plugins?: Plugin[]
}

export const Chart = ({ data, options, type, plugins, updateMode, chartId }: IChartProps) => {
  const chartInstance = useRef<Chartjs<ChartType, DefaultDataPoint<ChartType>, unknown>>({
    update: noop,
    destroy: noop,
  } as Chartjs)

  useEffect(() => {
    chartInstance.current.options = options
    chartInstance.current.data = data

    chartInstance.current.update(updateMode)
  }, [data, options])

  const nodeRef = useCallback<(instance: HTMLCanvasElement | null) => void>((node) => {
    chartInstance.current.destroy()

    if (node) {
      Chartjs.register(
        Tooltip,
        CategoryScale,
        LineController,
        LineElement,
        PointElement,
        LinearScale,
        TimeScale,
        Title,
        Annotation
      )

      chartInstance.current = new Chartjs(node, {
        type,
        data,
        options,
        plugins,
      })
    }
  }, [])

  return <canvas ref={nodeRef} id={chartId} />
}

Chart.register = Chartjs.register || noop
```

**Comment by paulhayessilex** [comment]
@kurkle thx so much, wouldn't have fixed this without your help

**Comment by paulhayessilex** [comment]
Are there types for this plugin?

**Comment by kurkle** [comment]
Version 1.0.0 has just been released.
