### ISSUE TITLE
shaded regions (box annotation) with chartjs 3

### ISSUE THREAD

**Issue by fetchinson** [chartjs/chartjs-plugin-annotation#218]
First of all Chart.js is a fantastic tool, it's just wonderful to work with. I've been using version 3 so far, everything is great and now I started looking into having shaded vertical regions, similar to this example:

https://moneyandmarkets.com/wp-content/uploads/2020/05/Federal-Reserve-data.png

And it looks like charts-plugin-annotation would be the perfect match for this, but am I right in thinking that it's not compatible with chartjs 3? 

I only need these shaded vertical regions right now, would this be simple to implement with chartjs 3? I don't mind doing it myself at all, but would be happy to get some pointers in the right direction.

**Comment by kurkle** [comment]
chart.js v3 support is in master already, stay tuned for a beta release in the next few days.
