### ISSUE TITLE
Draw vertical line using Labels

### ISSUE THREAD

**Issue by alejandrofm** [chartjs/chartjs-plugin-annotation#22]
I have text labels (dates) in my x-axis, how can I make a vertical line in, for example "17/8" I tried this and with x-axis-0 no error, no lines.
Any idea?
Thank you!
annotation: {
        annotations: [{
            type: 'line',
            mode: 'vertical',
            scaleID: 'x-axis-1',
            value: '17/08', 
            borderColor: 'DimGrey',
            borderWidth: 5
                 }]
}

**Comment by etimberg** [comment]
Do you have a test case or jsfiddle?

**Comment by alejandrofm** [comment]
I'll try to create a jfiddle, I have an ajax call and some dynamic code.
Thanks

**Comment by XanderKon** [comment]
Any news here? Can someone help with the same issue?

**Comment by gj1118** [comment]
@XanderKon were you able to resolve this issue ?  If yes , can you please post some sample code ?  

Thanks a ton. 

With Regards
Gagan
