### ISSUE TITLE
Cannot disable an annotation box / line

### ISSUE THREAD

**Issue by LaMigne** [chartjs/chartjs-plugin-annotation#221]
Hi,

I am trying to enable / disable annotations by clicking on a combobox.

The only thing I can disable is the caption (using the documentation), with this simple line :
`                myLine.options.annotation.annotations[0].label.enabled = false;
`

However I am looking for a way to disable also the line or box.

The alternative of making the line or box transparent is not good as the graph will not resize itself as it considers the annotation object is still here.

Is there a simpler way of doing this that I am missing ? I tried the following one with no success
`                myLine.options.annotation.annotations[0].enabled = false;
`

Cheers all and thank you :)

**Comment by kurkle** [comment]
You could workaround by setting the borderColor / backgroundColor to transparent.

**Comment by kurkle** [comment]
Fixed by #246

Most of the options are scriptable today, so you could write some custom logic for `display` option.
