### ISSUE TITLE
Jumpy/glitchy stacked animations

### ISSUE THREAD

**Issue by aandroyd** [chartjs/chartjs-plugin-annotation#225]
A single chart animation works fine the annotations plugin. However, if a second (or third, etc.) animation starts before the first has completed, all the annotations jump back to their original start position from the first animation. If animations keep stacking without ever finishing, the original position remains indefinitely and makes it look like all the annotations are glitching and jumping around independent of the native chartjs data. This can be fixed by disabling animations (or setting the duration to 0), but that only avoids the problem without fixing it if you _want_ animations.

See live example at [https://codepen.io/aandroyd/pen/ZEWBoPe]

chart.js 2.9.3 with chartjs-plugin-annotation 0.5.8

**Comment by Veda-cmd** [comment]
Add the following code in options.
Live link with fix : [https://codepen.io/vedant004/pen/RwaVzGz](url)
```
animation: {
        duration: 0
  }
```

**Comment by aandroyd** [comment]
Thanks for the response, but animation.duration=0 is the same as animation=false. That hides the glitchy behavior but then I have to give up animated data.

**Comment by arturaugusto** [comment]
Solved this problem by disabling / enabling animation:
```javascript
chart.options.animation.duration = 0
chart.annotation.elements['a-line-1'].options.value = newValue
chart.update()
chart.options.animation.duration = 400
```

**Comment by kurkle** [comment]
I've done some preliminary work for Chart.js v3 support:
https://codepen.io/kurkle/pen/oNLBxJB
