### ISSUE TITLE
Label hidden when draw line at top of chart

### ISSUE THREAD

**Issue by thaithanhdhv** [chartjs/chartjs-plugin-annotation#226]
![Screen Shot 2020-09-15 at 10 58 50](https://user-images.githubusercontent.com/39685046/93156169-89cc6f00-f742-11ea-8f26-5c6847f4ebfa.png)
I want to add a line with label at top of chart.
But the label is hidden.

**Comment by Veda-cmd** [comment]
You can set anchor to start or center
https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html

**Comment by thaithanhdhv** [comment]
> You can set anchor to start or center
> https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html

This is other plugin. How I can apply this to current plugin?

**Comment by Veda-cmd** [comment]
Use yPadding.

**Comment by jgrayson-apl** [comment]
set the axes '**offset**' property to **true** and it provides a little space above the chart that helps this issue
https://www.chartjs.org/docs/latest/axes/cartesian/#common-configuration

**Comment by yennor** [comment]
I've got the same problem, but with a vertical line and the y-axis on the left. Activating offset on the y axis didn't help. and moving the label with xAdjust looks ugly

**Comment by kurkle** [comment]
You could probably set the value to 100.1 and the scale would expand to next "nice" number.
