### ISSUE TITLE
React TypeScript - Annotations not rendering correctly.

### ISSUE THREAD

**Issue by robert-stevens** [chartjs/chartjs-plugin-annotation#228]
Hi,

My annotations are set to:

```
annotation: {
  events: ["onClick"],
  annotations: [{
    drawTime: "afterDraw" as "afterDraw",
    type: "box" as "box",
    xMin: "2 Sep",
    xMax: "4 Sep",
    yMin: 0,
    yMax: 50,
    backgroundColor: "green",
    borderColor: "red",
    borderWidth: 1,
    onClick: function (e: any) {
    //do something...
    },
  },],
},
```

And I initialise the Bar chart using:

```
<Bar
  data={data}
  height={height}
  options={options}
  plugins={[ChartAnnodation]}
 />
```

Which Renders:

![Screenshot 2020-10-05 at 16 23 03](https://user-images.githubusercontent.com/32265535/95091706-10afae80-0727-11eb-928d-f939d411dc55.png)

**The issue:**

I can't get the box annotation to fill the correct space, it simply fills all the space. I have tried different values for the min/max of both axis, but it makes no difference.

You will see that I have to set **drawTime** and **type** in a strange way, otherwise if I set them normally, I get the following type errors:

> Types of property 'type' are incompatible.
                Type 'string' is not assignable to type '"box"'.
  Overload 2 of 2, '(props: LinearComponentProps, context?: any): Bar', gave the following error.

I am not sure what I am doing wrong, or why it it would be throwing type errors.

I am using:

```
"@types/chartjs-plugin-annotation": "^0.5.1",
"chartjs-plugin-annotation": "^0.5.7",
"chart.js": "^2.9.3",
```

**Comment by Veda-cmd** [comment]
Your values are incorrect it seems.

**Comment by Veda-cmd** [comment]
One of snippets from examples:

```
{
            drawTime: "beforeDatasetsDraw",
            type: "box",
            xScaleID: "x-axis-0",
            yScaleID: "y-axis-0",
            xMin: "February",
            xMax: "April",
            yMin: randomScalingFactor(),
            yMax: randomScalingFactor(),
            backgroundColor: "rgba(101, 33, 171, 0.5)",
            borderColor: "rgb(101, 33, 171)",
            borderWidth: 1,
            onClick: function(e) {
              console.log("Box", e.type, this);
            }
          }
```

**Comment by kurkle** [comment]
I'd guess this is related to scale configuration (and/or the missing x/yScaleID)

**Comment by robert-stevens** [comment]
@kurkle @Veda-cmd tx

Does the x/yScaleID relate to the x/yAxisID?

I have updated the annotations to include the scaleIDs:

```annotation: {
    events: ["onClick"],
    annotations: [
        {
            drawTime: "afterDatasetsDraw" as "afterDatasetsDraw",
            type: "box" as "box",
            xScaleID: "x-axis-0",
            yScaleID: "y-axis-0",
            xMin: "3 Sep",
            xMax: "5 Sep",
            yMin: 0,
            yMax: 50,
            backgroundColor: "green",
            borderColor: "red",
            borderWidth: 1,
            onClick: function (e: any) {
                // console.log("Box", e.type, this);
            },
        },
    ],
},```

At which point no annotations render.

I had a look at the documentation in regards to the Bar chart:

https://www.chartjs.org/docs/latest/charts/bar.html#general

And see that I need to add in a xAxisID and yAxisID, which I have done:

```const data = {
    labels: labels,
    datasets: [
        {
            xAxisID: "x-axis-0",
            yAxisID: "y-axis-0",
            data: values,
        },
    ],
};```

And updated my scales:

```scales: {
    yAxes: [
        {
            id: "y-axis-0",
        },
    ],
    xAxes: [
        {
            id: "x-axis-0",
        },
    ],
},```

And still no annotation is rendering.

**Comment by Veda-cmd** [comment]
No need to update the ids in scales.
There is one point which is mentioned in Box Annotations:

> Box annotations are supported. If one of the axes is not specified, the box will take the entire chart dimension.

> The 4 coordinates, xMin, xMax, yMin, yMax are optional. If not specified, the box is expanded out to the edges

Your axes or values seem incorrect. Please try some variations of values and see if it is rendering.

**Comment by kurkle** [comment]
I can't spot any error in the values or config. Can you create a reproduce somewhere? It might be related on how the chart is initialized for react.

**Comment by robert-stevens** [comment]
When I remove the xScaleID from my annotations, it renders the annotation and if I change the yMin/Max values, the annotation shifts up/down vertically.

So it seems to do with the xScaleID and it's xMin/Max values.

When I put it back, nothing renders. I have tried different date values, but no matter what combination I use it simply doesn't render.

I wanted to know, I format the xAxes ticks:

```
ticks: {
    callback: function (value: string, index: number, values: any) {
        const date = new Date(value);
        return `${date.getDate()} ${date.toLocaleString("default", {
            month: "short",
        })}`;
    },
},
```

And as per the screenshot the ticks are render as 7 Aug, 14 Aug etc. while the data labels are still in the full format, e.g. Mon Aug 10 2020 02:00:00 GMT+0200 (South Africa Standard Time)

Does the xMin/Max values work off the tick values or off the (data) labels? Could this be causing the issue?

@kurkle ok, I will create an example for this.

**Comment by kurkle** [comment]
ah, the min/max for time scale work most reliably if specified as epoch, I do not remember if 2.9.3 parses the values using same method that it uses for data. That would be the 2nd option, use same format as in data.

**Comment by robert-stevens** [comment]
ah ok, i have formatted the labels and ticks to use the same format. it's working now.

@kurkle tx for the help.
