### ISSUE TITLE
Chart scales are not adjusted with annotations

### ISSUE THREAD

**Issue by svpace** [chartjs/chartjs-plugin-annotation#23]
The automatic scale does not account for the annotations. If I set an annotation with value greater than the data scale the annotation is drawn outside the chart area.

**Comment by etimberg** [comment]
At the moment, this is as designed. The chart fits to data, and annotations are not data. You can use the `max` option to set the scale to something above your annotation

**Comment by svpace** [comment]
Thank you for the quick reply.

The problem is that, as is, annotations overlap with the legend and scales. Shouldn't they be restrict to the chart area?

Regards

**Comment by etimberg** [comment]
They probably should be, or at least not drawn if outside the chart area
