### ISSUE TITLE
Labels with drawTime: beforeDatasetsDraw

### ISSUE THREAD

**Issue by joshkel** [chartjs/chartjs-plugin-annotation#243]
I wanted my datasets to be drawn on top of my line and box annotations, so I used `drawTime: 'beforeDatasetsDraw'`. However, that causes the datasets to overwrite the lines' and boxes' labels, which doesn't look good at all:

![image](https://user-images.githubusercontent.com/476338/97492629-300eb580-193a-11eb-8747-22584bc5433d.png)

It seems to me that, even if annotation lines and boxes are drawn below the datasets, the labels for those annotations should be drawn on top of datasets. (At least, I can't think of any circumstances where you'd want a text label but are okay with it being partially obscured by your data...)

I saw similar questions and discussions (#94, #147, #161), although my request is a bit different - I'm proposing moving label-drawing to a separate loop that's always after the datasets (ignoring `drawTime`), instead of #161's approach of moving label-drawing to a separate loop within the configured `drawTime`.

**Comment by kurkle** [comment]
Would it be good to have separated draw Time for labels?
There is some work towards z-index already in chart.js, but I think it would need a new hook and/or breaking the old ones (can't really have both z and afterDatasetsDraw)

**Comment by joshkel** [comment]
Yes, I'd be happy with a separate draw time for labels. (I really can't think of a time when you wouldn't want them after the datasets - but just because I can't think of something doesn't mean it's not useful.)

I'm happy to submit submit a PR if you like. (Possibly as an update to #161? It makes sense to handle the two together.)

I saw comments about a z-index for Chart.js but wasn't clear on how far along it was.

Thank you.

**Comment by kurkle** [comment]
I'm happy to review and merge a pr for that. Can be based on #161, but does not have to be. Pick the route that is easier for you.

**Comment by joshkel** [comment]
Done in #275
