### ISSUE TITLE
Set annotation value dynamicly

### ISSUE THREAD

**Issue by guasc0** [chartjs/chartjs-plugin-annotation#252]
Hi,
Im using chart js with annotation and draggable.
I want to set the annotation value dynamicly wich works fine from my dialog popup, can even disable it.
The draggable plugin only works when i set an id to the annotation but then i cant uppdate the annotation value dynamicly.

Any ideas how to get the draggable plugin to work without setting an id to the annotation ?

**Comment by kurkle** [comment]
Setting the value should not depend on the `id`. Are you possibly replacing the entire annotation when setting the value?

With latest beta version (and Chart.js v3) the value can be scriptable, so it gives you more possibilities on how to update it.

If you need further assisntance, please create an interactive example of your problem.
