### ISSUE TITLE
Feature Request: bracket annotation

### ISSUE THREAD

**Issue by danatcofo** [chartjs/chartjs-plugin-annotation#258]
![image](https://user-images.githubusercontent.com/418147/98617700-2c2d4c80-22c5-11eb-9f7c-d0633ab7d01b.png)

I would love to have the ability to do a bracket annotation as I am showing here in with the orange brackets in this terrible visual.  basically like the vertical or horizontal line in function except rather than a line, we get a caret or symbol of some type on top|bottom|left|right within the area outside the plot.

This would be really useful when there are a lot of series that need drawing and the annotation is easily lost.

**Comment by stockiNail** [comment]
@danatcofo just for my curiosity, could make sense to use a char (a char annotation), where with font size, color and rotation you can set whatever char you want (for instance curly or squared or round brackets) ?
Of course, using the canvas drawing, it's quite difficult to give the freedom to the user to use the symbol he/she wants. With chars could be easier.

**Comment by stockiNail** [comment]
@danatcofo is something like that?

![Issue258](https://user-images.githubusercontent.com/11741250/100747997-0e926500-33e3-11eb-98fa-e99590e45ff7.PNG)

This is done using 2 line annotations with the same value and the labels (1 on top and 1 on bottom) with y adjust.
If sounds good, you don't need to new annotation but you can use line annotation one with labels.

Nevertheless this is doable if the clipping on chart area will be configurable. At the moment it is not.
You also should pay attention that when you are drawing outside of chart area, you can override other elements (legend, title, ticks) or go out of the canvas (in this case you should set the `layout.padding` of chart.js options).

Annotation plugin options, used for the above sample (config of plugin for CHART.JS 3):

```javascript
plugins: {
   annotation: {
      drawTime: 'afterDatasetsDraw',
      annotations: {
         top: {
            type: 'line',
            scaleID: 'x',
            value: 'March',
            borderColor: 'transparent',
            label: {
               position: 'top',
               font: {
                  size: 48,
                  color: 'orange'
               },
               backgroundColor: 'white',
               borderWidth: 0,
               yPadding: 0,
               xPadding: 0,
               yAdjust: -22,
               rotation: 90,
               content: '}',
               enabled: true
            }
         },
         bottom: {
            type: 'line',
            scaleID: 'x',
            value: 'March',
            borderColor: 'transparent',
            label: {
               position: 'bottom',
               font: {
                  size: 48,
                  color: 'orange'
               },
               backgroundColor: 'white',
               borderWidth: 0,
               cornerRadius: 0,
               yPadding: 0,
               xPadding: 0,
               yAdjust: +22,
               xAdjust: 0,
               rotation: -90,
               content: '}',
               enabled: true
            }
         }
      }
   }
}
```

**Comment by danatcofo** [comment]
a character would work yes...   That looks nice...  but yes something like that would work wonderfully

**Comment by stockiNail** [comment]
@danatcofo I'm gonna wait for the merging of some PRs submitted and then I'd propose the possibility to draw out of chart area (at the moment that's not possible). The rest should be already done and available.
