### ISSUE TITLE
annotation does not shown in Vue environment

### ISSUE THREAD

**Issue by kenmasumitsu** [chartjs/chartjs-plugin-annotation#265]
Annotation is not shown in Vue project.

It is the demonstration codes of the problem.   (chartjs-plugin-annotation 0.5.7)
https://jsfiddle.net/kenmasu/Lgt7vpyx/1/

It is similar codes without Vue. It shows annotations expectedly. 
https://jsfiddle.net/kenmasu/hm6p0ou3/1/

It seems that Vue automatically change normal objects to  Vue Observable objects.
So that, the plugin failed to merge annotations (default annotations and given annotations) in initConfig() in helper.js.

I modified initConfig() and confirmed it fixed.
https://github.com/kenmasumitsu/chartjs-plugin-annotation/commit/3f5315f5648ff51b78fae6035b11a5e74d16194e
https://jsfiddle.net/kenmasu/r1xz9tLj/

**Comment by carlknappdev** [comment]
Can confirm, I'm running into the same issue as well. Attempting to pass the chart options via the Vue component's data function fails for me.

Passing the chart options as a plain object works fine.

**Comment by phil-w** [comment]
In my own case, which appears similar, the problem is with View 2.* and the annotation plugin version 0.5.7. 
Reverting the annotation plugin doesn't fix it, but regressing chart.js from 2.9.4 to 2.9.3 does "fix" it.

**Comment by arneesh** [comment]
Is there a published version for this fix that can be used? As I am using vue-chartjs and not directly chartjs, I can't simply downgrade the version directly, and yes @kenmasumitsu you are absolutely right about the issue, that what is happening in my props.

**Comment by nb1987** [comment]
l found the root cause for this issue. I filed an issue with the Chart.js repo at chartjs/Chart.js#8382 and also explained in an answer to a similar problem at https://stackoverflow.com/questions/64878459/annotation-dont-show-in-vue-chartjs/66058308#66058308
