### ISSUE TITLE
Label is cut due to rotation

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#271]
When you configure the `rotation` to the line label, the `x` and `y` (calculated interpolating the points on the line) are producing the following result:

![download](https://user-images.githubusercontent.com/11741250/100551367-40d78180-3280-11eb-8ea9-0851bcfb4737.png)

As you can see the label of red line is cut (due to the clip area).
The `x` and `y` calculation (by  `height` and `width` and `calculateLabelPosition` function) is assuming that the label has got rotation 0 but with different rotation,`height` and `width` of rotated label are changed and in cascade also`x` and `y`. 

With PR #266 which is calculating the vertex of label, it's possible to adjust the label position.
**I'm gonna submit a PR to fix it.**

Next enhancement could be to allow the user to draw outside of clip area (currently set to `chartArea`), maybe by an options (for instance `clip: true` (default)) in order that  issue #258 could be addressed as well.

**Comment by kurkle** [comment]
Thanks for all the pull requested. I'll try to get beta.7 of Chart.js out and when that is out, will focus here. So please be patient :)

**Comment by stockiNail** [comment]
@kurkle yes, no problem. I see you are deeply engaged to beta7 (I have read all discussion about plugin hooks, really interesting).
I have already fixed part of the this issue but I need more time as well to address all possible cases about label positions. 
I'm gonna wait your feedback before pushing anything.

Thank youuuu

**Comment by stockiNail** [comment]
@kurkle FYI, I fixed and now the labels are shown correctly. I'll take time to "optimized" my poor JS.
