### ISSUE TITLE
How do I install using npm with Chart.js 3.0.0-beta.6?

### ISSUE THREAD

**Issue by thezentrader** [chartjs/chartjs-plugin-annotation#272]
I am trying to install the plugin using npm using these dependencies: 

`"dependencies": {
    "chart.js": "^3.0.0-beta.6",
    "chartjs-chart-financial": "github:chartjs/chartjs-chart-financial#master",
    "chartjs-plugin-annotation": "github:chartjs/chartjs-plugin-annotation#master",
    "datatables.net": "^1.10.22",
    "datatables.net-bs4": "^1.10.22",
    "datatables.net-responsive": "^2.2.6",
    "jquery": "^3.5.1",
    "moment": "^2.29.1"
  }`

The npm install seems to work fine but I never actually get any src files in the node-modules folder. If I go look in the chartjs-plugin-annotation folder (in the node_modules directory), all I see are the LICENSE, README and package.json files. No other files seem to have been downloaded.

Any advice on installing this plugin the right way for Chart.js 3.0.0?

**Comment by dougfelton** [comment]
Have a look at the comment by joshkel in [this issue](https://github.com/chartjs/chartjs-plugin-annotation/issues/240).  Worked for me.

**Comment by kurkle** [comment]
published today as chartjs-plugin-annotation@next (compatible with chart.js-3.0.0-beta.7)
