### ISSUE TITLE
Box annotation starts from center of category axes

### ISSUE THREAD

**Issue by AmirHossein** [chartjs/chartjs-plugin-annotation#283]
I need box annotation the same as the purple box on the [example](https://codepen.io/compwright/pen/mmQMrZ) but it doesn't work as expected on my chart. I need it to be started and finished on axes lines, not the center!
<img src="https://user-images.githubusercontent.com/293169/102874256-745c9480-4457-11eb-8282-c7339d7e4d9b.png" width="80%" />

Here is the config:
 ```javascript
chart.options.annotation.annotations.push({
	drawTime: "beforeDatasetsDraw",
	type: "box",
	xScaleID: "x-axis-0",
	yScaleID: "y-axis-0",
	xMin: "2018 December",
	xMax: "2019 February",
	yMin: 0,
	yMax: 200000,
	backgroundColor: "rgba(101, 33, 171, 0.5)"
});
chart.update();
```
and scales config:
```javascript
"scales": {
	"yAxes": [{stacked: true}],
	"xAxes": [{stacked: true}]
}
```
Also Adding `absolute min/max` or `offset` parameters will be nice. 
Any help will be appreciated.

**Comment by kurkle** [comment]
You could try `1.5` for `xMin`

**Comment by AmirHossein** [comment]
`1.5` didn't work. No drawing, without any error.
The attached image above is what I am getting now, I need something like the purple box below:
<img src="https://camo.githubusercontent.com/9c4fa2e7a4f94fec5a95e3b6c0769eb5d5d8b5cd36c4a21e12dbbb86f37a9638/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f3932636d74387a72746835357a35352f53637265656e73686f74253230323031372d30352d323025323031382e32362e33392e706e673f7261773d31"/>

**Comment by danielissac** [comment]
![image](https://user-images.githubusercontent.com/20000698/104303800-8da1af80-54f0-11eb-9951-c71eef3f5576.png)

chart.js version 2.9
I'm also facing the same issue... the box annotation is not drawn from the beginning. do you got any solution on this @AmirHossein ? need support 4 this @compwright

**Comment by kurkle** [comment]
gridlines are offset, you can change that.

**Comment by AmirHossein** [comment]
@danielissac  Unfortunately, it didn't work for me.
I created the plugin below for my case:
```javascript
Chart.pluginService.register({
    id: "highlightBarColumns",
    beforeDatasetsDraw: function (chart, foo, options) {
        options = options || {};
        options.color = options.color || 'rgba(0,0,0,0.1)';
        options.indexes = options.indexes || [];
        var axeX = chart.scales[chart.config.options.scales.xAxes[0].id];
        var axeY = chart.scales[chart.config.options.scales.yAxes[0].id];
        var ctx = chart.chart.ctx;
        options.indexes.forEach(function (index) {
            if (axeX.ticks.length > index) {
                var tickPosition = axeX.getPixelForTick(index);
                var width = index > 0 ? tickPosition - axeX.getPixelForTick(index - 1) : axeX.ticks.length > 1 ? axeX.getPixelForTick(index + 1) - tickPosition : axeX.width;
                var x = tickPosition - width / 2;
                var y = axeY.getPixelForValue(axeY.max);
                var height = axeY.getPixelForValue(axeY.min) - y;
                ctx.fillStyle = options.color;
                ctx.fillRect(x, y, width, height);
                ctx.fill();
            }
        });
    }
});
...
var chart = new Chart(ctx, {
    ...
    options: {
        plugins: {
            highlightBarColumns: {
                color: 'rgba(0,0,0,0.1)',
                indexes: [1, 2, 5]
            }
        },
        ...
    }
});
```

**Comment by danielissac** [comment]
Great work. what u mean by indexes: [1,2,5] @AmirHossein ?

**Comment by AmirHossein** [comment]
@danielissac Index of columns. `[2, 3, 4, 5, 6]` in your screenshot.
