### ISSUE TITLE
[Request] - Publish to chartjs-plugin-annotation@next

### ISSUE THREAD

**Issue by technicallynick** [chartjs/chartjs-plugin-annotation#288]
So that users that would like to utilize the Chart.js beta and your package together, could you publish a beta release to your repository so that we don't have to jump through hoops to get it up in our environment for testing?

**Comment by kurkle** [comment]
Yeah, that is planned. Just some amount of free time away :)

**Comment by technicallynick** [comment]
> Yeah, that is planned. Just some amount of free time away :)

Great! Thanks for the fast reply!

**Comment by kurkle** [comment]
https://www.npmjs.com/package/chartjs-plugin-annotation/v/1.0.0-beta
