### ISSUE TITLE
`display` callback and lazy initialization of elements

### ISSUE THREAD

**Issue by joshkel** [chartjs/chartjs-plugin-annotation#298]
The current implementation of the `display` property creates new, empty annotation objects as needed, but it only populates those objects if the element is displayed. This creates a couple of issues:

* When the chart is first shown, the element parameter that's passed to the `display` callback is empty, so the callback doesn't have access to the information it needs to determine if the element should be shown.
* If an annotation is hidden (via `display: false` or returning false from a callback), then the chart is updated (via a call to `chart.update()`), then chartjs-plugin-annotation tries to process the empty annotation object and generates errors. See https://codepen.io/joshkel/pen/GRjBMQM for an example.

https://github.com/chartjs/chartjs-plugin-annotation/blob/3741a30d230e201fc8e9f961e31e650a5245387f/src/annotation.js#L112-L123

**Comment by stockiNail** [comment]
>     * When the chart is first shown, the element parameter that's passed to the `display` callback is empty, so the callback doesn't have access to the information it needs to determine if the element should be shown.

@joshkel you are right. At the beginning, the display property was computed after the element initialization but , thinking to avoid useless calculation, it was located before the element init in order to avoid to do it if it doesn't have to be shown.
Maybe that's wrong.

I'm going to work on that and create a PR.

**Comment by stockiNail** [comment]
>     * If an annotation is hidden (via `display: false` or returning false from a callback), then the chart is updated (via a call to `chart.update()`), then chartjs-plugin-annotation tries to process the empty annotation object and generates errors. See https://codepen.io/joshkel/pen/GRjBMQM for an example.

@joshkel as you wrote, this is related to previous item. Nevertheless in the PR I'd like to add a filter, during the adjustment of scale range, in order to avoid to process elements do not be display

**Comment by stockiNail** [comment]
@joshkel about https://codepen.io/joshkel/pen/GRjBMQM, pay attention because you used the scales configuration of CHART.js 2 and not the new one for 3.

```javascript
    scales: {
      y: {
        beginAtZero: true,
      }
    },
```

**Comment by joshkel** [comment]
> about https://codepen.io/joshkel/pen/GRjBMQM, pay attention because you used the scales configuration of CHART.js 2 and not the new one for 3.

Thanks; I'd copied the CodePen from a Chart.js 2.x template and forgot to update that.

**Comment by joshkel** [comment]
Thanks for the quick fix!
