### ISSUE TITLE
Bar chart and box annotation

### ISSUE THREAD

**Issue by thibauds** [chartjs/chartjs-plugin-annotation#3]
I'm trying to add a box annotation on a bar chart,
https://jsfiddle.net/jxpx1kup/1/
As you can see this is not working as I expect it. Maybe I'm doing something wrong, but I think that when using bar chart, the function `getPixelForTick` should be used intead of `getPixelForValue` as you can see on this jsfiddle :
https://jsfiddle.net/jxpx1kup/

(The edited line is 53.)

**Comment by compwright** [comment]
This appears to be related to #35.
