### ISSUE TITLE
Support for finite lines (and diagonal lines?)

### ISSUE THREAD

**Issue by joshkel** [chartjs/chartjs-plugin-annotation#302]
The previous release of the plugin allowed line annotations to be configured with xMin, xMax, yMin, yMax, xScaleID, yScaleID. This meant that you could use the plugin to draw finite-length line segments as well as lines that extended for the entire chart.

![image](https://user-images.githubusercontent.com/476338/104215566-f3b20800-5406-11eb-9234-32d40acb5c2a.png)

It looks like this was undocumented (and unintended?). There were a few glitches; the min and max X and Y values were evaluated independently (so the first X could get paired with the second Y, so lines could go diagonally down and right but could not go diagonally up and right). Mouse events didn't properly evaluate lines' limits, so the `enter` event could be triggered if, e.g., the Y coordinate matched, even if the X was outside of the lines' boundaries. For simply drawing horizontal and vertical line segments, however, it worked.

After #263 was merged, however, each annotation type got its own code for resolving options, and so line annotations no longer piggybacked on top of box annotations' support for xMin, xMax, yMin, yMax, xScaleID, yScaleID, so I now get a diagonal line from the top left of the plot to the bottom right of the plot.

Would you be open to a PR that restores support for xMin, xMax, yMin, yMax, xScaleID, yScaleID and that fixes the two glitches I mentioned, so that chartjs-plugin-annotation can properly support finite line segments and diagonal lines?

**Comment by kurkle** [comment]
Yes, I suppose that feature was used. So PR is welcome!

**Comment by stockiNail** [comment]
I don't think this feature was intented because as @joshkel reported the points (start and end) were wrongly calculated for the line.

Nevertheless I was having a look. The calculation sounds quite simple to add in `resolveElementProperties` method, something like that:

```javascript
if (scale) {
   // scaleID
} else {
   // xScaleID - yScaleID
   const xScale = chart.scales[options.xScaleID];
   const yScale = chart.scales[options.yScaleID];

   if (!xScale && !yScale) {
     return {options: {}};
   }

   if (xScale) {
     x = scaleValue(xScale, options.xMin, x);
     x2 = scaleValue(xScale, options.xMax, x2);
   }

   if (yScale) {
     y = scaleValue(yScale, options.yMin, y);
     y2 = scaleValue(yScale, options.yMax, y2);
   }
}
```

The possible issue is that now the line annotation is calculating automatically if it's horizontal or vertical based on the configured scale.
I was thinking if makes sense to re-introduce the `mode` options (`horizontal` or `vertical`) or to calculate the angle of triangle and then if greater than 45 is vertical otherwise horizontal.

**Comment by kurkle** [comment]
Could change the positioning to `start`, `center` and `end`, to be orientation agnostic.

**Comment by stockiNail** [comment]
> 
> Could change the positioning to `start`, `center` and `end`, to be orientation agnostic.

I was thinking the same about the label position, but the orientation is also needed to calculate the auto rotation.
