### ISSUE TITLE
IE 11 Compatibility

### ISSUE THREAD

**Issue by elitastic** [chartjs/chartjs-plugin-annotation#313]
Has Internet Explorer 11 support been discontinued? There's lots of lambda functions in the beta version which isn't supported by IE 11..?

e.g. on line 19 in chartjs-plugin-annotation.esm.js:

```javascript
hooks.forEach(hook => {
    if (typeof options[hook] === 'function') {
      state.listened = true;
      state.listeners[hook] = options[hook];
    }
});
```

**Comment by stockiNail** [comment]
@elitastic the plugin is based on CHARTJS v3 which dropped the compatibility on IE 11.
See https://github.com/chartjs/Chart.js/issues/8042

**Comment by elitastic** [comment]
Oh I somehow missed that, thanks for your quick reply!
