### ISSUE TITLE
Skewed line annotations

### ISSUE THREAD

**Issue by mrdnote** [chartjs/chartjs-plugin-annotation#32]
Hi, I think it would be useful if you could have skewed line annotations. I already got it working in my fork with 4 lines of code and adding an endValue option next to the existing value property.

![image](https://cloud.githubusercontent.com/assets/5628584/19595560/a178c8fc-97b4-11e6-9ea0-97d5a29c2832.png)

I can create a pull request if you'd like.

**Comment by etimberg** [comment]
@mrdnote that would make a great PR.

**Comment by compwright** [comment]
@mrdnote see #31. Maybe you could build off that.

**Comment by compwright** [comment]
Tagging #34. This issue can be closed @etimberg

**Comment by etimberg** [comment]
Thanks @compwright
