### ISSUE TITLE
Vertical Line, Boxes in bar chart

### ISSUE THREAD

**Issue by naninana** [chartjs/chartjs-plugin-annotation#334]
Looking at the example, which is using version 0.5.5 a vertical line added to the chart is displayed between the bars in a bar chart, on top of the grid line.
If I try to do the same with 0.5.7 the vertical line is now displayed on top of the bar.
Same applies to the boxes, in 0.5.5 they go from gridline to gridline, which allowed you to draw a border around some of the bars.

Is there still a way, to display the line or box like in 0.5.5?

**Comment by kurkle** [comment]
This is related to the category scale. You can specify the values as label indices and use fractions to go between.

For example, see: 
https://github.com/chartjs/chartjs-plugin-annotation/blob/master/test/fixtures/box/category-index.js
