### ISSUE TITLE
Question: How to use this plugin with React

### ISSUE THREAD

**Issue by luq10** [chartjs/chartjs-plugin-annotation#337]
I created a [demo](https://codesandbox.io/s/chartjs-xrzcp?file=/src/Chart.js) and I have no idea why annotation don't show. What I'm doing wrong?

**Comment by kurkle** [comment]
couple of reasons:

1. Defaults scale id's in Chart.js v2 are in the form: "x-axis-1"
2. v0.57 plugin reads its options from `config.options.annotation`, so you need to remove the `plugins` from between.

**Comment by luq10** [comment]
Awesome, this works! Thanks @kurkle 

I think that documentations need to be updated about this things.
