### ISSUE TITLE
Scriptable context for scriptable options

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#348]
Currently all options are scriptable.

The context that is passed as argument is a context of type `chart`.

You don't have any reference to the options of plugin or to the annotation element.

Is that the architectural decision?

In my opinion, at least the options should be passed in the context and maybe the context could be typed differently from `chart`, maybe marked as `annotation`.

Some thing like the following:

## Option Context

The option context is used to give contextual information when resolving options and currently only applies to [scriptable options](#scriptable-options).
The object is preserved, so it can be used to store and pass information between calls.

There are multiple levels of context objects:

* `chart`
  * `annotation`

Each level inherits its parent(s) and any contextual information stored in the parent is available through the child.

The context object contains the following properties:

### chart

* `chart`: the associated chart
* `type`: `'chart'`

### annotation

In addition to [chart](#chart)

* `element`: plugin element which contains also the options
* `type`: `'annotation'`

**Comment by kurkle** [comment]
There is a 2nd argument to the scriptable function that contains other options in current scope.
But I agree with you that we should provide `annotation` context.
