### ISSUE TITLE
Not numerical min and max values

### ISSUE THREAD

**Issue by geraldo** [chartjs/chartjs-plugin-annotation#35]
Great plugin! I really would like it to apply to date ranges, putting min and max-values like that:
```
yMin: '2016-06-01'
yMax: '2016-07-01'
```

**Comment by compwright** [comment]
Have you tried `yMin: new Date('2016-06-01')`?

If that doesn't work, you can use a linear scale instead of a date scale, and use a custom tick formatter to format UNIX timestamps as date strings. Then you could do this:

`yMin: new Date('2016-06-01').getTime()`

**Comment by thegruffalo** [comment]
I had the same issue with a barchart with a non numeric scale. My tweak was in the LineAnnotation configure function 

`if (scale) {
	pixel = helpers.isValid(options.value) ? scale.getPixelForValue(options.value) : NaN;
	endPixel = helpers.isValid(options.endValue) ? scale.getPixelForValue(options.endValue) : pixel;
}`

->

`if (scale) {
	pixel = scale.getPixelForValue(options.value);
	endPixel = scale.getPixelForValue(options.endValue || options.value);
}`

I didn't try your suggestion to use a custom tick formatter as I didn't think of it.
