### ISSUE TITLE
Label rotation not working

### ISSUE THREAD

**Issue by nakigami** [chartjs/chartjs-plugin-annotation#358]
Hi, 
I'm using ChartJs 2.9.4 with the annotation plugin 0.5.7, but when i add the rotation property to the label object it doesn't work, here is the code i'm using : 
                        let chosenDay = days.indexOf(day);
                        let labelPosition = '';
                        if (chosenDay === 0 ) {
                            labelPosition = 'end';
                        }
                        else if (chosenDay === 6) {
                            labelPosition = 'start';
                        } else {
                            labelPosition = 'center';
                        }
                        Chart.helpers.each(Chart.instances,(instance) => {
                            instance.options.annotation.annotations.push({
                                type: 'line',
                                mode: 'vertical',
                                scaleID: 'x-axis-0',
                                value: chosenDay.toString(),
                                borderColor: randomColor(1),
                                borderWidth: 2,
                                label: {
                                    backgroundColor: 'rgba(126,152,168,0.8)',
                                    fontFamily: 'sans-serif',
                                    fontSize: 12,
                                    fontStyle: 'bold',
                                    fontColor: '#fff',
                                    cornerRadius: 4,
                                    rotation:  90,
                                    enabled: true,
                                    content: label
                                }
                            });

Thanks in advance.

**Comment by stockiNail** [comment]
@nakigami I think the `rotation` options was enabled with PR #178 (merged on Mar 24, 2020).
The version 0.5.7 was published on Oct 19, 2017, therefore I think the feature is not there.

**Comment by nakigami** [comment]
Okey thank you.
