### ISSUE TITLE
Uncaught Error: class does not have id

### ISSUE THREAD

**Issue by marcusround** [chartjs/chartjs-plugin-annotation#387]
I am new to using any sort of Chartjs plugin so maybe I am doing something silly.

But I can't get this plugin to work. I have Chart.js 3.0.2 and chartjs-plugin-annotation 0.5.7

I am using Webpack and was able to get Chartjs working fine, but couldn't import annotation without the following error.
Simply commenting/uncommenting the line `Chart.register(annotationPlugin)` will toggle the error.
To do a minimal example I just reduced down to a file with nothing but [this code from the docs](https://www.chartjs.org/chartjs-plugin-annotation/guide/integration.html#bundlers-webpack-rollup-etc):

```
import { Chart } from 'chart.js';
import annotationPlugin from 'chartjs-plugin-annotation';

Chart.register(annotationPlugin);
```

And that results in the same error

```
Uncaught Error: class does not have id: function(chartInstance) {
			var chartOptions = chartInstance.options;

			// Initialize chart instance plugin namespace
			var ns = chartInstance.annotation = {
				elements: {},
				options: helpers.initConfig(chartOptions.annotation || {}),
				onDestroy: [],
				firstRun: true,
				supported: false
			};

			// Add the annotation scale adjuster to each scale's afterDataLimits hook
			chartInstance.ensureScalesHaveIDs();
			if (chartOptions.scales) {
				ns.supported = true;
				chartHelpers.each(chartOptions.scales.xAxes, setAfterDataLimitsHook);
				chartHelpers.each(chartOptions.scales.yAxes, setAfterDataLimitsHook);
			}
		}
    register chart.esm.js:4468
    _exec chart.esm.js:4594
    _each chart.esm.js:4586
    each helpers.segment.js:109
    _each chart.esm.js:4584
    _each chart.esm.js:4579
    add chart.esm.js:4536
    value chart.esm.js:5768
    js barChart.js:63
    Webpack 5```

**Comment by kurkle** [comment]
You'll need to use the `@next` pre-release of this plugin with Chart.js v3. I'd expect a full release quite soon though.

**Comment by marcusround** [comment]
Thank you, that worked.
