### ISSUE TITLE
default values does not not take in account when resolving annotation options

### ISSUE THREAD

**Issue by xslavkov** [chartjs/chartjs-plugin-annotation#397]
## Setup
- "react": "^17.0.2",
- "chart.js": "^3.0.2",
- "chartjs-plugin-annotation": "^1.0.0",

```
import Annotation from 'chartjs-plugin-annotation';
...
data={ ... }
options={ {
    ....
    annotations: [ {
	drawTime: "afterDatasetsDraw",
	id: "hline",
	type: "line",
	mode: "horizontal",
	scaleID: "yAxes",
	value: 62,
	borderWidth: 2
    } ]
} }
plugins={ [ Annotation ] }
```

## Description
I was struggling to get this to work quite some time. No example worked for me. Sometimes event some error of undefined poped out.

And it seems that default values are not take in account when resolving annotation options. It started to work after suggested fix.

## Fix suggestion
Modify **resolveObj** in **annotation.js** as follows
```
function resolveObj(resolver, defs) {
  const result = {};
  for (const name of Object.keys(defs)) {
    const optDefs = defs[name];
    const value = resolver[name];
	result[ name ] = isObject( optDefs )
		? resolveObj( value ? value : {}, optDefs )
		: value
			? value
			: optDefs;
  }
  return result;
}
```

**Comment by kurkle** [comment]
From the README:

> This plugin needs to be registered. It does not function as inline plugin

Looks like this note is not in docs.

**Comment by xslavkov** [comment]
I confirm, registered plugin works out of the box.

I wonder tough. That was the second thing that i did after installing it and back then it did not work. And when looking to codes i saw: 
```
chart_js.Chart.register( Annotation );
```
From this i though it might not need to be registered anymore.

I suppose that options format was incorrect back then and when i started to messing up i forgot to register it again. All examples I found specified options as
```
annotation: {
    ...
    annotations: [...]
}
```
