### ISSUE TITLE
Font object in the label is not scriptable 

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#399]
Implementing all scriptable options of the plugin, I have seen that the `font` option of label in the line annotation is not scriptable except by scripting every single property of the `font` object.

```javascript
font: (ctx) => {size:18},   // does not work

font: {
  size: (ctx) => 18 // does not works
 },   
```
In CHART.JS and other plugins, the font is a scriptable options which manage the whole object and I think it makes more sense because it is also more performing.

Maybe an enhancement for next version.

**Comment by stockiNail** [comment]
@kurkle you're right! I don't know why I didn't see it.. Thanks!

**Comment by stockiNail** [comment]
@kurkle I have also implemented and tested in my lib and it works... Sorry for useless issue :(

**Comment by kurkle** [comment]
No worries :)
