### ISSUE TITLE
Line chart: Nothing happen

### ISSUE THREAD

**Issue by fega** [chartjs/chartjs-plugin-annotation#40]
Hello I'm trying to implement the plugin with the code:
```
var aqiChart = new Chart($("#aqi-chart"), {
  type: 'line',
  data: {
    labels: [0,100],
    datasets: [{ //AQI LINES
      label: 'aqi',
      data: [100,100]
    }]
  },
  options: {
    spanGaps: true,
    defaultColor: '#FF1744',
    scales: {
      type: 'time',
      xAxes: [{
        type: "time"
      }]
    }
  },
  annotation: {
    annotations: [{
      type: 'line',
      mode: 'horizontal',
      scaleID: 'y-axis-0',
      value: 10,
      borderColor: 'black',
      borderWidth: 3
    }]
  }
});
```
but nothing happen, can you help me?

**Comment by compwright** [comment]
Can you try it with a linear scale, and let us know if it works that way? That will narrow down whether we have an issue rendering on that kind of scale.

**Comment by brentp** [comment]
@fega, your annotation block needs to be inside the options

**Comment by compwright** [comment]
Yep, that would do it. Good catch. @fega you can re-open this if that doesn't fix it for you.

**Comment by fega** [comment]
Thanks!, @brentp and @compwright ,
