### ISSUE TITLE
Dist files missing?

### ISSUE THREAD

**Issue by KoalaBear84** [chartjs/chartjs-plugin-annotation#405]
Just discovered this plugin, which is great, thanks for that!

It looks like the cdnjs version doesn't update anymore, and I'm not sure if that is because there is no "dist" folder anymore?

https://cdnjs.com/libraries/chartjs-plugin-annotation

See the issue I just created:

cdnjs/packages#697

**Comment by jimaek** [comment]
It appears to be present only in npms
https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@1.0.0/dist/chartjs-plugin-annotation.min.js

**Comment by kurkle** [comment]
We don't host dist files in github. Looks like cdnjs is configured to use the repository to get the package, which does not work.

https://www.npmjs.com/package/chartjs-plugin-annotation
https://www.jsdelivr.com/package/npm/chartjs-plugin-annotation
https://unpkg.com/chartjs-plugin-annotation@1.0.0/dist/chartjs-plugin-annotation.min.js
https://www.skypack.dev/view/chartjs-plugin-annotation

etc.
