### ISSUE TITLE
sourceMappingURL error in dist/chartjs-plugin-annotation.min.js

### ISSUE THREAD

**Issue by jonblatho** [chartjs/chartjs-plugin-annotation#407]
Very minor issue here, but when using this plugin on my site, I receive an error because `dist/chartjs-plugin-annotation.min.js` references a source map file that does not exist:

    Failed to load resource: the server responded with a status of 404 (Not Found)
    http://localhost:1313/js/chartjs-plugin-annotation.min.js.map

For clarity, the `dist/` directory from `node_modules/chartjs-plugin-annotation/` is mapped into `js/` on my site using a static site generator.

**Comment by danaoxmt** [comment]
Versions
chartjs-plugin-annotation: ^1.0.0
chart.js: ^2.9.4

I think I have found a similar issue. The plugin is attempting to import chart.js/helpers for a few methods, but I think this has been merged into the main chart.js distribution so it fails to to find the file. Currently can't import the plugin.

**Comment by emmachase** [comment]
@danaoxmt You are using version chart.js 2.9.4, the README states that if you are using chart.js < 3.0.0, you should use version 0.5.7 of the annotation plugin.
