### ISSUE TITLE
cannot resolve chart.js/helper file 

### ISSUE THREAD

**Issue by francose** [chartjs/chartjs-plugin-annotation#412]
I m getting this error below after installing the package. I have tried removing the node modules and reinstalling all, it didn’t work. any suggestions?

`Module not found: Can't resolve 'chart.js/helpers' in  .....  /node_modules/chartjs-plugin-annotation/dist'
`

**Comment by kurkle** [comment]
What version of chart.js and chartjs-plugin-annotation do you have? How are you integrating (importing, requiring) them?

**Comment by francose** [comment]
I m importing the package. 

` import "chartjs-plugin-annotation";`
` "chart.js": "^2.9.4",
    "chartjs-plugin-annotation": "^1.0.0",
    "chartjs-plugin-datalabels": "^1.0.0",`

**Comment by kurkle** [comment]
chartjs-plugin-annotation 1.0.0 works with chart.js ^3
You need to use 0.5.7 with chart.js v2.

https://github.com/chartjs/chartjs-plugin-annotation#readme
https://www.chartjs.org/chartjs-plugin-annotation/guide/
