### ISSUE TITLE
Box annotation labels

### ISSUE THREAD

**Issue by brentp** [chartjs/chartjs-plugin-annotation#42]
AFAICT, labels are not supported on box annotations, it would be nice if they were added.

**Comment by compwright** [comment]
You are correct. Feel free to submit a PR ;)

**Comment by RomeoDenis** [comment]
@JewelsJLF  can you please do a PR? we are seriously in need of it

**Comment by tomhatzer** [comment]
@JewelsJLF any news on your PR?

**Comment by JewelsJLF** [comment]
Sorry, this fell off my radar. I'll see if I can find some time in the next
few days.

**Comment by pwlgr** [comment]
@JewelsJLF any updates on the PR? Cheers

**Comment by gj1118** [comment]
Any updates please ? Please confirm 

Thanks

**Comment by JewelsJLF** [comment]
No, sorry... I haven’t been using chartjs in a while.  Still plan to find
some time for this, but it hasn’t happened yet.

**Comment by JewelsJLF** [comment]
Sorry I haven't done a pull request, but here is the code that we were using for this when we needed this feature last year...

[chartjs-plugin-annotation.js.txt](https://github.com/chartjs/chartjs-plugin-annotation/files/3351595/chartjs-plugin-annotation.js.txt)

**Comment by beingtechie** [comment]
I wonder, why this feature was not published, i think this is must need feature

**Comment by kgirma** [comment]
I do not know either. Seems like the only major feature lacking from this awesome plugin.

**Comment by kgirma** [comment]
> Sorry I haven't done a pull request, but here is the code that we were using for this when we needed this feature last year...
> 
> [chartjs-plugin-annotation.js.txt](https://github.com/chartjs/chartjs-plugin-annotation/files/3351595/chartjs-plugin-annotation.js.txt)

Is there an implementation guide for this? Thanks.

**Comment by Djones4822** [comment]
I'm wondering if anyone has made progress on this issue for chartjs-v3? I have been reviewing the source code and I believe I have a plan of implementation.

It appears that all the annotation types except Line are missing a few methods: `labelIsVisible()`, `isOnLabel()`, and `drawLabel()`, as well as the default settings for the label. 

However I also see a number of helper functions like `calculateLabelPosition()`, `measureLabel()`, `calculateT()`.... and then obviously the `drawLabel()` 

I think the `calculateT()` would need to be implemented for the box type to make sure `calculateLabelPosition()` returns correctly...

I haven't gone through Jewels' implementation, or the sitting pull request, but I assume they have solved the `calculateLabelPosition()` questions.

Anyone have any insight before I embark?
