### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by ukandrewc** [chartjs/chartjs-plugin-annotation#434]
Just downloaded the minified .js V.1.0.2, which I'm using with chartJS V3.3.2 and added it to html:

```
	<script src="chart.min.js"></script>
	<script src="datalabels.min.js"></script>
	<script src="annotation.min.js"></script>
```
DataLabels is working, but Annotation isn't, is there anything else I need to do?

Thanks

**Comment by ukandrewc** [comment]
Just tried it with the sample from the docs, which works, so must be me!

**Comment by ukandrewc** [comment]
This stops annotations from drawing:

	scales: {
		xAxes: {
			display: false,
			max: maxRate * 1.2
		},
		yAxes: {
			display: false,
		}
	},

Using x/y instead of xAxes/yAxes is OK

**Comment by kurkle** [comment]
What type of annotation and did you specify scaleID/xScaleID/yScaleID?

**Comment by ukandrewc** [comment]
I didn't, I've only just got started so not yet familiar with all the options and properties.
