### ISSUE TITLE
JS Critical Error 

### ISSUE THREAD

**Issue by TheGreatHammer** [chartjs/chartjs-plugin-annotation#435]
There is a web application that was deployed in another server. and our department wanted to move it from one web server to another. so when i tried to run it on my local machine. i keep getting a JS error as follows:

JavaScript critical error at line 1, column 619 in http://localhost*path of the file*\n\nSCRIPT1004: Expected ';'

I tried using another version of chartjs and it didn't work.

Thank you in advance

**Comment by kurkle** [comment]
It looks like you are bundling something and the budle ends up being invalid. 
There is no hint that your error is somehow related to this plugin.

**Comment by TheGreatHammer** [comment]
> It looks like you are bundling something and the budle ends up being invalid.
> There is no hint that your error is somehow related to this plugin.

Ok, how can i know if the bunlding is not valid. I saw the bundling file, but it's a huge code with 17k lines.
Note: I did not work on the project, neither can i find the team who worked on it. So i'm on my on :(

**Comment by kurkle** [comment]
Can't really help without the code, and even with the code I suspect it would be out of scope.
