### ISSUE TITLE
Have an issue with box annotation. 

### ISSUE THREAD

**Issue by marathea** [chartjs/chartjs-plugin-annotation#438]
Face the problem as documented here - https://stackoverflow.com/questions/68229521/chart-js-multiple-box-annotations-displays-only-the-last-box 

It works good if I don't use date labels. But once I start using date labels it doesn't work. Can you please check? Thanks.

**Comment by kurkle** [comment]
The problem is in your scale config that is in chart.js v2 format. Additionally you were missing a date-adapter required by the time scale and the parser string for your timestamps.

https://jsfiddle.net/5cqxth2r/
