### ISSUE TITLE
Incorrect type for CoreAnnotationOptions.borderDash

### ISSUE THREAD

**Issue by jbrunton** [chartjs/chartjs-plugin-annotation#461]
Hi,

The type given for [`borderDash`](https://github.com/chartjs/chartjs-plugin-annotation/blob/f0966577b4e8a7874e02443db9c1350992aeb364/types/options.d.ts#L26) in `CoreAnnotationOptions` is `Scriptable<[number, number], PartialEventContext>`, i.e. it expects an array with precisely two numbers. This is inconsistent with the [docs](https://www.chartjs.org/chartjs-plugin-annotation/guide/types/line.html#configuration), which suggest the type should be `number[]`.

Is this a mistake in the type definition? I believe `number[]` is the intended type. If so, I'd be happy to submit a PR to fix.

**Comment by kurkle** [comment]
`borderDash` is passed to [setLineDash](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash) so `number[]` seems correct.

**Comment by kurkle** [comment]
I'd be happy to review a PR for this
