### ISSUE TITLE
Annotations labels overlapping

### ISSUE THREAD

**Issue by girardHU** [chartjs/chartjs-plugin-annotation#462]
Sorry if this is a duplicate but I cannot seem to find something related to my issue. I would like to know if there is a way for one of the label to be automatically displayed a little lower if they overlap ? Or not displayed at all maybe ?

Thanks,

![image](https://user-images.githubusercontent.com/52254161/134007109-0f38abd3-186d-45df-906d-fc46caae94ca.png)

**Comment by kurkle** [comment]
Currently not possible automatically, so labeling as enhancement

**Comment by stockiNail** [comment]
@girardHU as @kurkle has written, this feature is still not present.
Neverthelss, leveraging on `yAdjust` and `xAdjust` on the label, you can change the position of the label, avoiding overlapping.
Could be a workaround, waiting for new feature.

See here an example: https://codepen.io/stockinail/pen/WNOKmbK
