### ISSUE TITLE
Plugin breaks after specifying xAxis scale

### ISSUE THREAD

**Issue by exo-pla-net** [chartjs/chartjs-plugin-annotation#468]
If you specify config.options.scales.xAxis = {}, it will break without an error. No annotations will appear.

If you specify config.options.scales.x = {}, it works fine.

If you specify config.options.scales.yAxis = {}, it works fine.

There's something weird going on with config.options.scales.xAxis.

**Comment by kurkle** [comment]
Nope?

![image](https://user-images.githubusercontent.com/27971921/137841778-9c1944a8-e47e-4dbe-8154-160cecab3679.png)

**Comment by kurkle** [comment]
See `xScaleID`: 
https://www.chartjs.org/chartjs-plugin-annotation/guide/types/box.html#configuration
