### ISSUE TITLE
defaults like in ChartJs

### ISSUE THREAD

**Issue by elitastic** [chartjs/chartjs-plugin-annotation#470]
Is there a way to set [default options](https://www.chartjs.org/docs/latest/configuration) as it is possible in ChartJs?

I would like to change some default options of all my annotations in several charts in one place:

`label.font.style = 'normal'` for annotation type `line`;
`label.xPadding=4` for annotation type `line`;
`label.yPadding=2` for annotation type `line`;
`drawTime='beforeDraw'` for all annotation types

**Comment by kurkle** [comment]
You can  set the defaults, after the plugin is registered, in `Chart.defaults.plugin.annotation`

**Comment by elitastic** [comment]
Unfortunately, this doesn't really help me. We have about 50 charts, all of which have very different annotations.

If I see this correctly, `Chart.defaults.plugin.annotation` only helps to globally add annotations.

But that's not a big deal for me, I solved it by using a own class to define annotations like:

```
import { autoinject } from 'aurelia-framework';
import { AnnotationOptions, AnnotationType } from 'chartjs-plugin-annotation/types/options';
import { FontSpec } from 'chart.js';
import { DeepPartial } from 'chart.js/types/utils';

export class Annotation<TYPE extends AnnotationType>
{
    constructor(annotation: DeepPartial<AnnotationOptions>)
    {
        annotation.drawTime = annotation.drawTime ?? 'beforeDraw';

        if (annotation.type == 'line' && annotation.label)
        {
            annotation.label.enabled = annotation.label.enabled ?? true;
            annotation.label.font = annotation.label.font ?? {
                style: 'normal'
            } as FontSpec;
            annotation.label.xPadding = annotation.label.xPadding ?? 4;
            annotation.label.yPadding = annotation.label.yPadding ?? 2;
        }

        if (annotation.type == 'box')
        {
            annotation.borderWidth = annotation.borderWidth ?? 0;
        }

        Object.keys(annotation).forEach(key =>
        {
            this[key] = annotation[key];
        });
    }
}
```

**Comment by kurkle** [comment]
Looks like I did not really read what I was answering to. Those are annotation element options, so the defaults can be configured in `Chart.defaults.elements.boxAnnotation` for example.

The element `id` and its defaults set at registration can be seen from the source:
https://github.com/chartjs/chartjs-plugin-annotation/blob/16b68b7133b23b560d20362591dfedfb9c40d855/src/types/box.js#L87-L102
