### ISSUE TITLE
Check "Scales" options first to continue

### ISSUE THREAD

**Issue by yusufozturk** [chartjs/chartjs-plugin-annotation#49]
Before processing, need to check "Scales" options if it's null or not. Some charts like "Pie chart" etc. may not have "Scales" options.

![image](https://cloud.githubusercontent.com/assets/928600/21547945/8309506a-cde9-11e6-9c8a-12b7d5dbf775.png)

Error line:
https://github.com/chartjs/chartjs-plugin-annotation/blob/master/src/annotation.js#L36,L37

**Comment by lefterisnik** [comment]
A quick workaround about this until PR to be merged is:
```
scales:{
  yAxes: [],
  xAxes: []
},
```
