### ISSUE TITLE
Docs for line talk about boxes

### ISSUE THREAD

**Issue by ersimont** [chartjs/chartjs-plugin-annotation#504]
Here are a couple snippets from the [documentation for lines](https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/types/line.html). It speaks of rectangles and boxes. Maybe it's stuff that was copy-pasted from the documentation for boxes and needs to be removed/adjusted?

> If one of the axes does not match an axis in the chart, the box will take the entire chart dimension. The 4 coordinates, xMin, xMax, yMin, yMax are optional. If not specified, the box is expanded out to the edges in the respective direction.

> borderRadius | Radius of box rectangle

**Comment by stockiNail** [comment]
> If one of the axes does not match an axis in the chart, the box will take the entire chart dimension. The 4 coordinates, xMin, xMax, yMin, yMax are optional. If not specified, the box is expanded out to the edges in the respective direction.

That's a mistake.

> borderRadius | Radius of box rectangle

I agree it's not well explain but the meaning of `box` is the box rectangle, container of the text label, I guess.

**Comment by ersimont** [comment]
> I agree it's not well explain but the meaning of box is the box rectangle, container of the text label, I guess.

Just to be sure we're looking at the same thing: `borderRadius` appears twice on the page. Only one of them is under the Label heading. I was referring to the first one, which is under the Styling heading. Not sure if that changes anything - I was assuming only the second one meant the container of the text label and the first was some kind of mistake.

**Comment by stockiNail** [comment]
@ersimont yes, the mention of `borderRadius` in styling section is wrong and must be removed.

> I was assuming only the second one meant the container of the text label and the first was some kind of mistake.

Exactly.

As soon as I've got time, I'm going to submit a PR to change it.

**Comment by stockiNail** [comment]
@ersimont about the mention of borderRadius in styling section, I didn't find it because it was already fixed in the master.

See doc (the development version): https://www.chartjs.org/chartjs-plugin-annotation/master/guide/types/line.html#styling

**Comment by stockiNail** [comment]
PR #505 submitted
