### ISSUE TITLE
Clipped area on chart cuts the label annotation

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#511]
Before drawing every annotation, the plugin clips an area equals to the chart one.

With LABEL annotation, positioning it with respect of the point, could be cut because should be drawn outside of the chart area, due to its calculated dimension.

![Screenshot 2021-11-30 185937](https://user-images.githubusercontent.com/11741250/144102876-9db3de69-1e81-4482-aaea-cd7bcf0a8fec.png)

For this reason, the dimension of the label annotation should take care about the available space around, in the chart area.

**Comment by kurkle** [comment]
I think both are valid use cases, so it should be behind an option.

For example when zooming, one could want the label to be clipped at the chart area border.

**Comment by stockiNail** [comment]
> For example when zooming, one could want the label to be clipped at the chart area border.

Ok, therefore we could add a boolean option (for instance `clip`) and then if set to `true`, this behavior is accepted, if `false`, the label is adjusted to the chart area.
Something like that?
