### ISSUE TITLE
Point of attention: clip: false and events catching on annotations

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#531]
The PR #523 added `clip` options in order to enable the annotation drawing even if part of them are outside of chart area.

And that's good but this is disabling the events catching on the part drawn outside of the chart.
The events are managed using the `beforeEvent` hook of the plugin which is invoked for events generated inside the chart area.
In this way, if the user clicks or moves on a visible annotation out of chart area, events are not dispatched to events hooks.

If the above thought is not wrong (please correct me), there are some possible solutions that I see:

1. stay as is but maybe we should document it in order that the user can add own events listeners to the canvas, ignoring the events hooks of the plugin. 
2. remove the usage of `beforeEvent` hook, going to the canvas event listeners.
3. ask to change this behavior to Chart.js but I don't think it makes sense.

**Comment by kurkle** [comment]
That analysis seems right to me.

I think it would be good if the plugin could indicate to chart.js if it wants events outside chart area. I would like to keep using the event hooks and improving those so plugin does not have to manage the listeners.

So maybe it would best to document that now, and update when/if there is an update to chart.js event handling.
