### ISSUE TITLE
Normalize all annotation to be based on box model (x, y, width, height)

### ISSUE THREAD

**Issue by kurkle** [chartjs/chartjs-plugin-annotation#532]
For consistency and thus easier handling of annotations regardless of type. 

Could be used for rough collision detection for example.

**Comment by stockiNail** [comment]
Proposal, maybe can help:

![elementProps](https://user-images.githubusercontent.com/11741250/145609678-792aac72-2cf0-4bb7-9b05-464a605e8d80.png)

**Comment by stockiNail** [comment]
REMINDER: Breaking change: https://github.com/chartjs/chartjs-plugin-annotation/pull/655#issuecomment-1024531750

**Comment by stockiNail** [comment]
This normalization will also enable (with common "properties"):

1. inner labels components (in line and box annotation) as sub-elements, based on the box
2. animation of labels
