### ISSUE TITLE
Inconsistent implementations of `inRange`

### ISSUE THREAD

**Issue by kurkle** [chartjs/chartjs-plugin-annotation#535]
Every implementation should accept the same arguments. `useFinalPosition` is not accepted by all types.

Edit: ellipse, line and polygon remain to be fixed

**Comment by stockiNail** [comment]
@kurkle polygon doesn't use any element property to check if the event is in range, because is using the vertices calculated in the draw function.
That said, `useFinalPosition` sounds to be useless for polygon. I can use it only to use it and to keep the method aligned with the other annotations.

**Comment by stockiNail** [comment]
Here the cose, using `useFinalPosition`. Anyway the vertices will not be animated therefore sounds useless to use the final position.  

```javascript
  inRange(mouseX, mouseY, useFinalPosition) {
    const {vertices} = this.getProps(['vertices'], useFinalPosition);
    return vertices && vertices.length > 0 && pointIsInPolygon(vertices, mouseX, mouseY);
  }
```
