### ISSUE TITLE
Hidden label when using position: "top" on vertical line label

### ISSUE THREAD

**Issue by buejoh** [chartjs/chartjs-plugin-annotation#55]
**Version: 0.5.3**

Using position: "top" results in a hidden label when using vertical line annotation.

Changing line 852 in the source code from

`ret.x = (isFinite(line.m) ? line.getY(ret.y) : view.x1) - xa;`

to 

`ret.x = (isFinite(line.m) ? line.getX(ret.y) : view.x1) - xa;`

fixes this issue. Maybe just a typo?

**Comment by compwright** [comment]
I believe so, yes. Feel free to submit a PR.
