### ISSUE TITLE
animations is not optional in types and is missing from documentation

### ISSUE THREAD

**Issue by kurkle** [chartjs/chartjs-plugin-annotation#559]
Since this commit, I have the following error in my project (when I try to upgrade this library):
> error TS2741: Property 'animations' is missing in type '{ annotations: { [key: string]: AnnotationOptions<keyof AnnotationTypeRegistry>; }; }' but required in type 'AnnotationPluginOptions'.

Shouldn't the `animations` property be optional ?
```diff
- animations: Record<string, unknown>,
+ animations?: Record<string, unknown>,
```

I don't find any documentation on this property in https://www.chartjs.org/chartjs-plugin-annotation/latest/ ; am I missing something ?

Thanks!

_Originally posted by @jbelien in https://github.com/chartjs/chartjs-plugin-annotation/pull/448#discussion_r768806334_

**Comment by kurkle** [comment]
@stockiNail do you have anything more you'd like in v1.2?

**Comment by stockiNail** [comment]
> @stockiNail do you have anything more you'd like in v1.2?

No, I don't! Thank you @kurkle

**Comment by jbelien** [comment]
Thanks a lot for this quick fix! 😃
