### ISSUE TITLE
Typescript compile error on 1.2.0

### ISSUE THREAD

**Issue by LouiMinister** [chartjs/chartjs-plugin-annotation#563]
![스크린샷 2021-12-15 오후 1 54 08](https://user-images.githubusercontent.com/33686751/146128750-acafe048-6fab-4f90-9935-d801a31df197.png)

I used library on angular, but after 1.2.0 update, angular build failed.
I think it's a bug on typescript compiling

**Comment by kurkle** [comment]
Typescript version in use?

**Comment by LouiMinister** [comment]
Version 3.8.3

**Comment by kurkle** [comment]
@LouiMinister would you be able to update to 4.1+? (that would make it work)


If we decide that we are supporting typescript < 4.1, then there are couple of options.

1. only use syntax acceptable by the lowest version of typescript we decide to support
2. use `typesVersions` and split the types by typescript version.

I tried to implement the 2nd option, but found no easy way to do it DRY.
It would essentially mean having 2 sets of types (and maintaining both).

@etimberg thoughts?

**Comment by LouiMinister** [comment]
If you decide to support only typescript 4.1+ I think you have to update readme. 
I downgraded this library as a workaround. 
After you handling about  typescript < 4.1, I will upgrade it. 
Thanks for your work.

**Comment by etimberg** [comment]
I am not opposed to older Typescript versions. Is there any way to get stats on which TS versions are in use and supported? I don't really want to support an older version that isn't used that much.

**Comment by priyankverma3pg** [comment]
Experinencin the same, any workaround apart from updating to TS
