### ISSUE TITLE
Annotations broken when using array syntax

### ISSUE THREAD

**Issue by elitastic** [chartjs/chartjs-plugin-annotation#572]
When writing annotations in array syntax, I get the following error (since version 1.2.0):

`Cannot read properties of undefined (reading 'borderCapStyle')`

Reproduction:
- go to https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/label/basic.html
- change the code like this:

from
```
annotation: {
  annotations: {
    annotation1,
    annotation2,
    annotation3
  }
}
```
to 
```
annotation: {
  annotations: [
    annotation1,
    annotation2,
    annotation3
  ]
}
```

**Comment by kurkle** [comment]
Fixed by: https://github.com/chartjs/Chart.js/pull/9969 (not released yet)

I think this only affects the new types.

**Comment by elitastic** [comment]
Thanks for your help!
