### ISSUE TITLE
annotation disappear if value is 0 (zero)

### ISSUE THREAD

**Issue by EmilMoe** [chartjs/chartjs-plugin-annotation#58]
I have an annotation that has the value 0, but then the annotation just disappear.

Any tricks to make it appear?

**Comment by compwright** [comment]
Please post a jsfiddle or CodePen reproducing your issue so we can help you figure it out. Thanks!

**Comment by EmilMoe** [comment]
sorry i didn't return. anyway i can see it's an error for me, i changed one of your examples and that works!

https://jsfiddle.net/LhkLx32a/

**Comment by broncode** [comment]
Hi, I have the same issue. A line annotation with the value 0 disappears from the chart. You can quickly reproduce it on the documentation page [here](https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/line/basic.html).

https://user-images.githubusercontent.com/37307452/149543538-b705c058-70d2-4756-8b5a-06f6a90f74f0.mp4

**Comment by stockiNail** [comment]
@broncode thank you very much. There is a bug in the update scale limits. PR will submit soon.
