### ISSUE TITLE
Examples don't work for anything other than scatter

### ISSUE THREAD

**Issue by vdh** [chartjs/chartjs-plugin-annotation#59]
The examples / documentation for this plugin is completely bare. Even if I try copying the examples, changing anything even slightly in the example data causes the annotations to vanish.

**Comment by compwright** [comment]
Please post a jsfiddle or CodePen that reproduces your issue so we can address it. Thanks!

**Comment by franckysolo** [comment]
I've got the same issue with bar and line
just trying to draw an horizontal line
here's my jsFiddle
https://jsfiddle.net/5y1u01ew/
