### ISSUE TITLE
Enable event handlers to indicate chart should be re-drawn

### ISSUE THREAD

**Issue by kurkle** [chartjs/chartjs-plugin-annotation#593]
Chart.js allows plugins to set `args.changed`, so the chart can re-render automatically after processing the event completely. This is important when there are many plugins that require re-draws. It gets slow and messy if every plugin does the draw (or update!) in their event handlers.

So I think these handles should be allowed to set/return a flag indicating a redraw should be done.

_Originally posted by @kurkle in https://github.com/chartjs/chartjs-plugin-annotation/issues/589#issuecomment-1002426614_

**Comment by stockiNail** [comment]
@kurkle Iagree, nevertheless the `click` event is asynchronous in order to manage `dblclick`, therefore these updates could affect only `enter`, `leave` and `dblclick`.
Maybe you should think again if `dblclick` is really needed.

**Comment by kurkle** [comment]
> Maybe you should think again if dblclick is really needed.

Should find out if anyone is using that. I don't think I have ever.

**Comment by stockiNail** [comment]
> Should find out if anyone is using that. I don't think I have ever.

Neither do I

**Comment by stockiNail** [comment]
> Should find out if anyone is using that.

Any idea how? Opening a discussion? Scanning projects in github?
