### ISSUE TITLE
Events don't bind to labels

### ISSUE THREAD

**Issue by harblz** [chartjs/chartjs-plugin-annotation#60]
onclick, onmouseover, etc. do not bind to the label text box.

This can be pretty confusing for users; they'll expect that the title will also trigger events (e.g., such as displaying a modal with information about phase changes or events in a data set).

![annotation](https://cloud.githubusercontent.com/assets/3269708/24580118/a2c5ac8e-16d0-11e7-95db-62020ed4c2f5.png)

**Comment by etimberg** [comment]
Looks like a bug in the event handler code. I'm happy to look at a PR fixing this
