### ISSUE TITLE
Annotation not working if ticks converted to date

### ISSUE THREAD

**Issue by karthiksd9** [chartjs/chartjs-plugin-annotation#61]
Annotation is not drawing for the below code. Can someone please suggest what is wrong in the below code?

Below is the fiddle: 
https://jsfiddle.net/oz51504g/2/

How to plot date field in annotation? 
I want to plot a horizontal line in 45 degree angle from the starting point. How can i achieve it?

Thanks in advance.

**Comment by compwright** [comment]
You generally need to specify the desired `scaleID` for the annotation. You can see it working here: https://jsfiddle.net/oz51504g/3/

**Comment by karthiksd9** [comment]
@compwright . Thanks a lot. It was that simple :D worked Great.
