### ISSUE TITLE
Cannot read property 'Annotation' of undefined     at Object.6../annotation.js?please find some solution for this i am struck in that error after give its reference 

### ISSUE THREAD

**Issue by heenaMahajan** [chartjs/chartjs-plugin-annotation#62]
Uncaught TypeError: Cannot read property 'Annotation' of undefined
    at Object.6../annotation.js (chartjs-plugin-annotation.js:451)
    at s (chartjs-plugin-annotation.js:10)
    at e (chartjs-plugin-annotation.js:10)
    at chartjs-plugin-annotation.js:10

**Comment by etimberg** [comment]
Do you have a test case for this?

**Comment by compwright** [comment]
Closing since there is no test case. @heenaMahajan please provide a CodePen reproducing your issue and then we can re-open this.
