### ISSUE TITLE
Annotations are not drawn if the id is `animations` or `label`

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#625]
If you set an annotation with id is equals `animations` or `label`, the annotations is not drawn on the chart.

Config example:

```javascript
annotations: {
  label: {
    type: 'point',
    xScaleID: 'x',
    yScaleID: 'y',
    xValue: 5,
    yValue: 5
  }
}
```
This seems to be related to the fallback because `animations` and `label` are 2 properties of annotations defaults and are objects.

Codepen: https://codepen.io/stockinail/pen/JjrmRBR

EDIT: the annotations are not drawn because `drawTime` is undefined.

**Comment by stockiNail** [comment]
Updated codepen with applied PR #630.

https://codepen.io/stockinail/pen/JjrmRBR

The label is not shown. Now drawTime is retrieved but `display` options is `false`, but it should be `true`.
If you set `display` to `true`, the font color is white and not black as is defined in label annotation default.

**Comment by stockiNail** [comment]
@kurkle I have done some tests and I see that `_fallback` is invoked with `props = 'annotations'`, uses `lineAnnotation` and this seems not correct and is generating this behavior.

https://github.com/chartjs/chartjs-plugin-annotation/blob/a74a6fc4b5ea4d009d8f8baba549a2b79d940768/src/annotation.js#L127-L130

Checking if  `props = 'annotations'`, returning `undefined` otherwise `elements.${annotationTypes[resolveType(opts.type)].id}`, it works well

**Comment by kurkle** [comment]
> @kurkle I have done some tests and I see that `_fallback` is invoked with `props = 'annotations'`, uses `lineAnnotation` and this seems not correct and is generating this behavior.
> 
> https://github.com/chartjs/chartjs-plugin-annotation/blob/a74a6fc4b5ea4d009d8f8baba549a2b79d940768/src/annotation.js#L127-L130
> 
> Checking if `props = 'annotations'`, returning `undefined` otherwise `elements.${annotationTypes[resolveType(opts.type)].id}`, it works well

I discovered the same thing. Though my test branch is a mess, so feel free to submit the PR for that.
BTW, remove the dblClickSpeed from defaults that was accidentally re-added there.

**Comment by stockiNail** [comment]
> BTW, remove the dblClickSpeed from defaults that was accidentally re-added there.

Already done in PR of line annotation label

**Comment by stockiNail** [comment]
Unfortunately what I proposed doesn't work for all test cases. I need to rethink

**Comment by stockiNail** [comment]
I think we should stay as is and closer this issue.
Nevertheless `common` config node is not documented and ts type is missing. I'll submit a PR for that.
