### ISSUE TITLE
Release 0.5.3

### ISSUE THREAD

**Issue by JemarJones** [chartjs/chartjs-plugin-annotation#64]
Issue #55 was fixed in January with d24ffaa6d93a0af52b309a490008d3a7b40523b0, yet the latest release available on npm is 0.5.2 and doesn't include this fix. Was the release of 0.5.3 forgotten?

**Comment by compwright** [comment]
Oops! Thanks for flagging this.

**Comment by JemarJones** [comment]
No problem! When do you think this release will be made?

**Comment by compwright** [comment]
Actually 0.5.3 does not include the fix to #55. That will be in a future release. 0.5.3 was a maintenance release that included a fix to package.json to facilitate getting this into cdn.js.

**Comment by compwright** [comment]
I would like to include PRs #50 and #54 along with #55 in 0.5.4 if possible. That's been the only holdup. I will try to find the time this week or weekend to wrap those up. If you feel like taking a crack at them, please do so.

**Comment by JemarJones** [comment]
Okay i understand, i will have to just deal with using `position: center` in the meantime. I would try to help with those issues but am not familiar enough with the plugin at the moment and haven't the time. Thanks for all your work!
