### ISSUE TITLE
Line is diagonal if yAxis options set

### ISSUE THREAD

**Issue by victorbnl** [chartjs/chartjs-plugin-annotation#676]
If no title is set for yAxis, it behaves correctly, there is an horizontal line

<img src="https://user-images.githubusercontent.com/39555268/153296467-581823ed-ee88-41f6-b722-6a9bc57a5be6.png" width="600px">

But if we set a title, the line becomes diagonal:

<img src="https://user-images.githubusercontent.com/39555268/153296579-30562716-8209-4488-ab3f-9a74d9cc9e91.png" width="600px">

## To reproduce,

Go on https://www.chartjs.org/chartjs-plugin-annotation/master/guide/types/line.html#configuration and add in the options:

```javascript
scales: {
    yAxis: {
        title: {
            display: true,
            text: "My First Dataset"
        }
    }
},
```

**Comment by victorbnl** [comment]
Update: it's not only with a title, it's for everything that uses yAxis; it even works with

```
scales: {
    yAxis: {}
},
```

**Comment by victorbnl** [comment]
Update 2: it's because these options makes the Y axis ID become `yAxis` while chartjs-plugin-annotation expects it to be `y`.

Two solutions:

1. Use `y` as the ID:

    ```js
    scales: {
        y: {
            // ...
        }
    },
    ```

2. Specify the name of your axis in chartjs-plugin-annotation's options:

    ```js
    plugins: {
        annotation: {
            annotations: {
                _: {
                    yScaleID: 'yAxis'
                }
            }
        }
    }
    ```

**Comment by stockiNail** [comment]
@victorbnl thank you very much for feedback.

As of Chart.js version 3, the default axes ids are `x` and `y` and this is the reason why the plugin is using `x` and `y` as default for `x/yScaleID` options.

I think `x/yAxis` is coming from Chart.js version 2 where the axes were defined in `x/yAxes` options as an array of axes.

As you can see from plugin documentation, https://www.chartjs.org/chartjs-plugin-annotation/master/guide/types/line.html#configuration, `x/yScaleID` have got a default and is reported in the documentation (see last column of the options table).

![image](https://user-images.githubusercontent.com/11741250/153360596-d412c233-ea50-4a2b-b17c-f22f68287098.png)

How do you think we can improve it that documentation?

**Comment by kurkle** [comment]
I think we could improve the defaults to be the first axes in the chart, which would mean you only need to specify when more than two scales  are involved. That would be a breaking change, so something to consider for v2.

**Comment by stockiNail** [comment]
Maybe there is not a breaking change because if you are using it, you are already defining which axis you want, if not it will use the what it's defined in the chart and therefore it will be x/y and nothing should change.

**Comment by victorbnl** [comment]
I totally agree! And maybe chartjs' documentation should use x and y for the samples, maybe I could make them a pull request
