### ISSUE TITLE
Add Label to Annotations

### ISSUE THREAD

**Issue by Adondriel** [chartjs/chartjs-plugin-annotation#7]
Add Label to the different types to specify what each value is representative of.
Text should be placed near line, or on a hover over. If I have time I will try to work on this.

**Comment by Adondriel** [comment]
Also, to add onto this, add a way to view the actual value of the reference line, preferably by hovering, or another method if more suitable.

**Comment by Adondriel** [comment]
current work is being done in my fork: https://github.com/Adondriel/Chart.Annotation.js since I don't have access to create a branch on this repo.

**Comment by ed-parry** [comment]
Hi @Adondriel - Great work on this - been looking for labels on annotations for a while and this works very nicely - ties into the default font settings as well. 

The only issue I discovered with it is when I hover over an existing tooltip on a data series (Line graph), the labels temporarily disppear while the tooltip is displayed. Any ideas on why that may be? I haven't had chance to dive into the code to see yet.

**Comment by Adondriel** [comment]
Ah, yea I had fixed that but forgot to push it, I made the label more of a badge, because I ended up finding that the label would often overlap other items, I also made it so that the line is behind the tooltip popup as well.

**Comment by etimberg** [comment]
Looks great @Adondriel 
If you can, feel free to PR a change to chart.js adding the on hover and then your changes to the annotation plugin :smile:

**Comment by Adondriel** [comment]
Lol, that may take a bit. I got a couple more tickets to take care of before I could start on that ATM. It may happen eventually.

**Comment by etimberg** [comment]
Yup!

**Comment by ed-parry** [comment]
Makes sense, @Adondriel! I wonder if there's scope for somehow including the line annotations (and their labels) in the chart key?

**Comment by Adondriel** [comment]
@ed-parry Would you mind elaborating on that? I'm not sure what you mean? Do you mean so that you can hide/show the line annotations? like how you can with the diff datasets?

**Comment by etimberg** [comment]
@Adondriel I think @ed-parry is referring to the chart legend. I think this might be possible, but it could be a lot of work

**Comment by compwright** [comment]
This is added in v0.3.0.
