### ISSUE TITLE
Interaction axis options default in the samples is not xy

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#718]
Default interaction options in the samples are set to 'x' instead of 'xy' as expected.

https://github.com/chartjs/chartjs-plugin-annotation/blob/70078ccbe49568f6a4106667ad008bef7edf5495/docs/scripts/defaults.js#L9-L13

**Comment by kurkle** [comment]
Why is `xy` expected?

**Comment by stockiNail** [comment]
Ok, doable. Nevertheless, my opinion as user, I'm expecting to go to the samples and to have the default chart options (in this case interaction is not) because if I'm adding the interaction to the sample, it seems the user should always do. But that's my point of view and maybe I'm wrong.  Anyway, let me change the PR following your hint.

**Comment by kurkle** [comment]
I'm ok removing the defaults and setting in the samples where required. Its better that way. I think the current defaults are to make the charts work in an opinionated way, which is not good.

**Comment by stockiNail** [comment]
> I'm ok removing the defaults and setting in the samples where required. Its better that way. I think the current defaults are to make the charts work in an opinionated way, which is not good.

Already done
