### ISSUE TITLE
Multiple Annotation Support

### ISSUE THREAD

**Issue by kavimaluskam** [chartjs/chartjs-plugin-annotation#72]
It would be great if we can add multiple annotation to one chart.

I have tried to pass multiple annotation object to **options: annotation: annotations** but sounds it does not work.

May i ask for any hints or this functionality is not supported?

**Comment by compwright** [comment]
It is supported, see the samples folder for examples. If you have a CodePen that reproduces the issue you are having someone here might be able to point out what is wrong.

**Comment by kavimaluskam** [comment]
Appreciate for you quick response. Sounds it should be my personal mistake. Multiple line annotation can be done.

Yet sorry to ask another problem.
For cases like below: https://codepen.io/kavimaluskam/pen/bRYXVR
for overlapping annotation, do you have any suggestion solving the issue? can we adjust the height of the label to avoid the label overlapping issues?

**Comment by kavimaluskam** [comment]
Sorry that i have read the readme.md more in detail, and also the source code of line.js.
Sounds it can be set to different height with different yAdjust as:
```javascript
position: 'center',
xAdjust: 0,
yAdjust: 120,
```

I think the issue can be closed.
