### ISSUE TITLE
multi-annotation label covered by line

### ISSUE THREAD

**Issue by lyf1988** [chartjs/chartjs-plugin-annotation#75]
I am using two line annotations to show two different values.

I found if two lines are too close the label for first annotation are covered by second line.

Here is example on codepen: https://codepen.io/angelo_lee/pen/LLmvpQ

Is there any settings to avoid this problem?

**Comment by compwright** [comment]
You can play with the `drawTime` setting and see if it fixes your issue. It controls when in the stacking order the annotations are drawn.
