### ISSUE TITLE
Error in strict mode

### ISSUE THREAD

**Issue by alexanderyarm** [chartjs/chartjs-plugin-annotation#76]
I have an error using box annotation in `strict mode`
`Uncaught ReferenceError: min is not defined`

Error at this line https://github.com/chartjs/chartjs-plugin-annotation/blob/master/src/types/box.js#L19

Variable has to be declared. The same for `max` variable

CodePen to reproduce an error:
https://codepen.io/alexanderyarm/pen/XgBqBM

**Comment by compwright** [comment]
Fixed in https://github.com/chartjs/chartjs-plugin-annotation/releases/tag/v0.5.6
