### ISSUE TITLE
textAlign property not working as I expect

### ISSUE THREAD

**Issue by elitastic** [chartjs/chartjs-plugin-annotation#768]
`textAlign: 'start'` is probably broken. Shouldn't this label annotation be left aligned on the zero x axis? Many thanks in advance for a short feedback.

![image](https://user-images.githubusercontent.com/6397763/177706653-28814862-3d26-44e1-92d0-e016b006a2b9.png)

https://codepen.io/elitastic/pen/JjLGmeY

**Comment by stockiNail** [comment]
@elitastic `textAlign` is used only when the content is an array (multiline text) to define the alignment of all rows.

What you need here is the `position` option. Try `position: 'start'`, it should work.

**Comment by stockiNail** [comment]
@elitastic I forgot... have a look to the doc: https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/types/label.html#position

**Comment by elitastic** [comment]
Thank you very much for your great support.
