### ISSUE TITLE
can't update an annotation file dynamically

### ISSUE THREAD

**Issue by soupmoth** [chartjs/chartjs-plugin-annotation#776]
for context I'm using ChartJS React 2, and am trying to present a "threshold" for a chart, that changes based upon the number of elements in another piece of data. Here's how I'm configuring the options.

`const options = {
      responsive: true,
      plugins: {
        legend: {
          display: false,
          position: 'top',
        },
        title: {
          display: true,
          text: 'Round 1',
        },
        
        annotation: {
          annotations: {
            line1: {
              type: 'line',
              yScale:  "y-axis-1",
              yMin: getThreshold(),
              yMax: getThreshold(),
              borderColor: 'rgb(255, 99, 132)',
              borderWidth: 2,
            }
          },
        }

      },
    };` 

GetThreshold() IS returning dynamic values, this is a screenshot of it doing just that
![image](https://user-images.githubusercontent.com/47698102/180669051-4dd153f0-2a01-432d-b4c6-4b8f58e332cb.png)

Is there anyway to do this with the framework I'm operating in?

**Comment by stockiNail** [comment]
@soupmoth I have created a codepen and it seems working: https://codepen.io/stockinail/pen/gOexgjq

Are you able to provide a codepen to have a look?

**Comment by soupmoth** [comment]
Sorry, I posted this when I was extremely tired. The yScale thing was a left over from me trying to find solutions from other issues opened here.

I tried making them scriptable options, and this worked! There was an error in my script too that I noticed because of this, so it was a big help! Thank you very much :)
