### ISSUE TITLE
Maximum call stack size exceeded when importing gobally

### ISSUE THREAD

**Issue by codeofsumit** [chartjs/chartjs-plugin-annotation#783]
When importing and registering the plugin globally, we get Maximum Call Stack Size Exceeded errors whenever we want to render a Pie or Doughnut chart.

We can't get it to work - the docs state it doesn't work with Pie charts which is fine but the error is probably not intended ?

**Comment by stockiNail** [comment]
As documented, `Annotations will not work on any chart that does not have exactly two axes, including pie, radar, and polar area charts.`
