### ISSUE TITLE
Decimal of float values for vertical annotations?

### ISSUE THREAD

**Issue by sahilweb6** [chartjs/chartjs-plugin-annotation#79]
how can we use decimal value for x-axis to represent and a vertical line using annotation.

```
annotation: {
                    annotations: [{

                        type: 'line',
                        mode: 'vertical',
                        scaleID: 'x-axis-1',
                        value: 4.5,

                        borderColor: 'green',
                        borderWidth: 4,
                        label: {
                            enabled: true,
                            content: 'Test label',

                        }
                    }]
                },
```
This code does not work and nothing appears.

But for value:4 it works well. Please let me know what  I have to do to make it support decimal values too

**Comment by compwright** [comment]
Floating point values should work fine with linear scales. See the samples in https://github.com/compwright/chartjs-plugin-draggable for a working example.
