### ISSUE TITLE
Label on type box for 0.5.7

### ISSUE THREAD

**Issue by florincod** [chartjs/chartjs-plugin-annotation#804]
Hi, 

There are any plans to add box type label for 0.5.7 version?
Or can be done differently? 
![image](https://user-images.githubusercontent.com/3803202/200513340-18065985-e820-4f0b-8a9a-bb6436e151cf.png)

**Comment by stockiNail** [comment]
@florincod no, there aren't. I'd suggest to go to version 2 where it has been implemented. Do you have any issue to go to version 2?

**Comment by stockiNail** [comment]
I understand. I think the version 0.5.7 is quite obsoleted and it has some bugs (and missing features) solved (and implemented) starting from version 1, where the plugin has been completely rewritten. I don't see any possibility to release new version 0.

**Comment by florincod** [comment]
@stockiNail, I found a solution, with some adjustments you can do it with type: line which has label prop

**Comment by stockiNail** [comment]
You're right. you can position a line over the box and hide the line (borderWidth: 0 or borderColor: transparent, I guess).
