### ISSUE TITLE
Remove autocolors plugin from doc going to ootb Chart.js color plugin

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-annotation#811]
Currently the documentation and the samples are using autocolors plugin.

Now the annotation plugin is based on CHART.JS 4 where there is new ootb plugin, `colors`, which is applying the colors automatically.

@kurkle @LeeLenaleee before submitting the PR, I need to drop my repo and fork this one again because the master branch is not aligned (my fault some months ago). To do that, I'm waiting for the PRs currently submitted.

**Comment by kurkle** [comment]
Chekout the master branch and do 'git reset --hard upstream/master'  and 'git push -f' after that succeeds. No need to drop.
