### ISSUE TITLE
How can I show image as annotation label?

### ISSUE THREAD

**Issue by nijatmursali** [chartjs/chartjs-plugin-annotation#813]
I'm working on one project and I need to show my `flag` image and I have checked this library and added annotation, but it does not show image. I have checked [documentation ](https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/line/image.html), but there is `Utils.getImage()` function used to get image. I'm using plain html(cdns for both chartjs and this library) and Javascript.

I get following result: 
![image](https://user-images.githubusercontent.com/16105077/203555335-21ac99f0-f19e-4579-8422-8e47619e156e.png)

but I want to show `flag` image. 

My annotation object is like this:

```
const annotation = {
            type: 'line',
            borderColor: 'red',
            borderWidth: 2,
            display: (ctx) => ctx.chart.isDatasetVisible(1),
            label: {
                content: "/assets/flag.png",
                display: true,
                content: '',
                position: 'start'
            },
            scaleID: 'x',
            value: 3.9
        };

```

**Comment by stockiNail** [comment]
@nijatmursali I have seen your question in [SO](https://stackoverflow.com/questions/74546596/how-to-calculate-and-show-monthly-cost-in-chartjs). About the look and feel of the chart, yes it's possible to have it as you put in the picture.

**Comment by nijatmursali** [comment]
Thank you, I have added it as image source and it worked, partially. I want to have only image without `backgroundColor`, but when I set the `backgroundColor: transparent` it removes the image as well. 

![image](https://user-images.githubusercontent.com/16105077/203559497-2d381f56-c778-427f-b403-69292a6a00d6.png)

**Comment by stockiNail** [comment]
The `backgroundColor` options doesn't affect the image if the image has got the background as transparent itself. It seems the the image doesn't have a transparent background.

I did a test with "backgroundColor: 'transparent'", and the image will always be shown. Try it in the sample: https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/line/image.html

**Comment by nijatmursali** [comment]
I think I have a problem with image itself. I need to double check it. Thank you for your help. Annotation part is solved. I need to figure out issue I shared on SO.

**Comment by nijatmursali** [comment]
Thank you. Hopefully I can get answer to it. Got some brain explosion by writing that code.

**Comment by stockiNail** [comment]
I have added a comment to SO to understand well what you need to calculate.

**Comment by nijatmursali** [comment]
Thank you, I added comment.

**Comment by stockiNail** [comment]
> Thank you, I added comment.

Answered.

**Comment by stockiNail** [comment]
@nijatmursali you can use `yAdjust` option, for instance `yAdjust: -100` means that the label is moved -100 pixels from original calculation (based on position 'start').

**Comment by stockiNail** [comment]
@nijatmursali apologize but I forgot to write you that you have to set also `clip: false` in the annotation.

```javascript
                    annotation: {
                        clip: false, // <-- must be added
                        annotations: {
                            annotation
                        }
                    }
```

**Comment by stockiNail** [comment]
@nijatmursali and I suggest you to add `layout.padding` to the chart options if you don't have any legend or title on top.

**Comment by nijatmursali** [comment]
Unfortunately it still gives similar behavior.. 
![image](https://user-images.githubusercontent.com/16105077/204502676-93f4804a-b0c8-44a1-bd94-fd897c5860e0.png)

**Comment by stockiNail** [comment]
@nijatmursali see my previous post.

Add space to the top of the chart, as following:

```javascript
options: {
  layout: {
    padding: {
      top: 32 //<- I suggest to set the height of the image and additional pixels
    }
  },
  scales: { .....
```

**Comment by nijatmursali** [comment]
Yes, it solved the issue thank you. Is it possible to set the height of annotation line?

**Comment by stockiNail** [comment]
Yes, you can.

You shoudl change the annotation config in order to indicate the limit you want:

```javascript
        const annotation = {
            type: 'line',
            borderColor: 'red',
            borderWidth: 2,
            display: (ctx) => ctx.chart.isDatasetVisible(1),
            label: {
                content: flag,
                display: true,
                backgroundColor: 'black',
                width: '30%',
                height: '30%',
                position: 'start'
            },
            // scaleID: 'x', --> must be removed and go to yScaleID
            // value: where --> must be removed and go to xMin and xMax
           xScaleID: 'x',
           yScaleID: 'y',
           xMin: where,
           xMax: where,
           yMin: 0,
           yMax: [what you want as max value and than you can limit the line]
        };
```

**Comment by nijatmursali** [comment]
Thank you. It solved the problem.

One last question, in mobile chart looks like this, but I set my width and height to 100% in my css for canvas.

```css
canvas {
    width: 100%;
  }
```
![image](https://user-images.githubusercontent.com/16105077/204529745-d453b122-7334-47f2-ad34-3f2f0f175681.png)

**Comment by nijatmursali** [comment]
`responsive` is set to `True` by default, but graph does not look responsive.
