### ISSUE TITLE
Horizontal bar chart not working

### ISSUE THREAD

**Issue by pokke123** [chartjs/chartjs-plugin-annotation#82]
When creating a normal Bar chart the annotations work see https://codepen.io/k3no/pen/yaGGGW
But when making it a horizontal bar chart the annotations stop working  see https://codepen.io/anon/pen/OjBePx

Thanks in advansed

**Comment by compwright** [comment]
Just need to reference the right orientation and scaleID combination.

https://codepen.io/anon/pen/dVwaap?editors=0010
