### ISSUE TITLE
Lines working in examples; but not on live code

### ISSUE THREAD

**Issue by bassman2112** [chartjs/chartjs-plugin-annotation#83]
Hello there,

I'm having a very strange issue where I am not able to draw any lines on any of my charts with our live code.

If I [run one of the examples](http://i.imgur.com/CVCtcqp.png) on its own, I can see the lines with no issues. 

However, if I copy and paste the exact same code onto my site, the [same chart will not display the lines](http://i.imgur.com/sDvXomL.png). 

I have ensured that I'm using exactly the same dependencies in both places (to the point where I copied the same files to their respective /js folders). I've ensured that we have no CSS touching any Canvas elements, so I am truly at a loss for why this is not working. 

Any tips for what else I should be looking at? Should I provide any code snippets?
Thank you!

**Comment by compwright** [comment]
Perhaps a file isn't loading correctly in your production environment, or a Javascript error is happening elsewhere that is breaking your code. Can't really tell without being able to access your site.
