### ISSUE TITLE
Draw line by index of yaxis

### ISSUE THREAD

**Issue by Giovancruz** [chartjs/chartjs-plugin-annotation#84]
Hey guys,

I have one page that shows "usage" in timescale chartjs, with update requests ... I dont know the values because they are dates and dynamic. I need to draw a line at index 0 and the last index (maybe something like -1).

How can I make the parameter start at beginning of index? Something like startIndex and stopIndex rather than value? #73

**Comment by compwright** [comment]
This isn't currently supported. We'll entertain a pull request to add the feature if you'd like to submit one.

**Comment by etimberg** [comment]
Very close to this working in 1.0.0-beta.4 https://jsfiddle.net/1wtd0qvf/1/

The issue is that the ticks are not created when the annotation is resolved.

**Comment by kurkle** [comment]
can be gotten around with simple test: https://jsfiddle.net/hgj2fx9d/

**Comment by etimberg** [comment]
The test doesn't work. If you change to `ticks[0]` it still renders at 0

**Comment by kurkle** [comment]
There is a timing issue alright
