### ISSUE TITLE
Image Opacity in LabelAnnotation

### ISSUE THREAD

**Issue by penedon** [chartjs/chartjs-plugin-annotation#844]
Hi all, I could not find a way to set the opacity of an image when using LabelAnnotation. When I have to use text, I can change the opacity by setting the opacity in the hex code in the `color` option.

So, is there an option to set the opacity?

**Comment by stockiNail** [comment]
@penedon good catch! At the moment, that's not possible by the plugin. You should manage the image by your code to have the opacity. But this is a good enhancement. I'm going to try and submit a PR for that.

**Comment by stockiNail** [comment]
@penedon FYI PR #846

**Comment by penedon** [comment]
Thanks @stockiNail!
