### ISSUE TITLE
Font config should be partial

### ISSUE THREAD

**Issue by oliviervanbulck** [chartjs/chartjs-plugin-annotation#848]
When using font config in an annotation, typescript gives an TS2739 error that says that you have to implement all font properties. Because this is an object that overrides the global font config, this should be partial so you can alter only specific elements.

![image](https://user-images.githubusercontent.com/11784648/217236669-80e2731f-f72e-4527-bfae-b846cc345c98.png)

**Comment by stockiNail** [comment]
PR #849 submitted
