### ISSUE TITLE
Annotations not updating when Chart is updated

### ISSUE THREAD

**Issue by daniel-shuy** [chartjs/chartjs-plugin-annotation#85]
When `chart.update()` is called, any changes in `options` should be re-rendered, however changes to `options.annotation` doesn't redraw the annotations on `update()`.

**Comment by daniel-shuy** [comment]
Sorry, my bad, I made a mistake, it works as intended.

**Comment by mwithi** [comment]
I'm having the same problem, @daniel-shuy what was your problem?

**Comment by Sanafan** [comment]
same problem here
