### ISSUE TITLE
UMD support (aurelia CLI)

### ISSUE THREAD

**Issue by lukpep** [chartjs/chartjs-plugin-annotation#86]
https://github.com/chartjs/chartjs-plugin-deferred/issues/2
I'm getting same problem:

> Uncaught TypeError: Cannot read property 'Annotation' of undefined
    at Object.i.6../annotation.js (vendor-bundle.js:sourcemap:49907)

Annotations still work thought. So basing on linked topic I'm guessing that umd support is needed (I checked gulp file - no umd pipeline there).
Any plans for supporting umd - needed by aurelia cli bundler?

**Comment by compwright** [comment]
No plans, but if we'll entertain a pull request to add the feature.

**Comment by etimberg** [comment]
Well out of date
