### ISSUE TITLE
Get other annotations width from an annotation scriptable option.

### ISSUE THREAD

**Issue by zk118** [chartjs/chartjs-plugin-annotation#865]
Hey, thank's for this usefull plugin !

I would like to get the width of an annotation from within another annotation scriptable option (to place the 2nd annotation next to the first relative to the width of the 1st annotation).

I want to accomplish something like that:

```
annotation1: {
	type: 'label',
	xValue: () => 0,
	yValue: () => 1,
	content: () => "Annotation 1",
	padding: 5,
	color: 'black',
},

annotation2: {
	type: 'label',
	xValue: () => 0,
	yValue: () => 1,
	xAjust: (cxt) => {
		return ctx.chart.options.plugins.annotation.annotations.annotation1.width
	},
	content: () => "Annotation 2",
	padding: 5,
	color: 'black',
}
```

But the problem is ctx.chart.options.plugins.annotation.annotations.annotation1.width doesn't exists.
Is it possible to achieve ?

Thanks in advance.

**Comment by stockiNail** [comment]
@evenmind the width of an annotation is a property of the annotation elements which are NOT exported (and then expose). 
There is a workaround to access to the elements but not documented and let me call it "private". 
Let me ask you if the center of the first label must be the point you selected or not. If not, you could use `position` option to align them.
Make sense for you?

**Comment by stockiNail** [comment]
Anyway, even accessing to the loaded elements, you don't know the width of the label you want to change therefore it's quite difficult I guess.

**Comment by evenmind** [comment]
I will check the private state in the meantime the next version is live, thanks.

**Comment by evenmind** [comment]
I get undefined for `window['chartjs-plugin-annotation']`

**Comment by stockiNail** [comment]
> I get undefined for `window['chartjs-plugin-annotation']`

Can you provide a sample to reproduce the issue?

**Comment by evenmind** [comment]
I literally just 

```
annotation2: {
	type: 'label',
	xValue: () => 0,
	yValue: () => 1,
	xAjust: (cxt) => {
		console.log(window['chartjs-plugin-annotation'])
	},
	content: () => "Annotation 2",
	padding: 5,
	color: 'black',
}
```

and get undefined. Maybe this is because I'm using vue-chartjs wrapper and it does not inject 'chartjs-plugin-annotation' in the window ?

**Comment by stockiNail** [comment]
> Maybe this is because I'm using vue-chartjs wrapper and it does not inject 'chartjs-plugin-annotation' in the window ?

Yes, I think so. I think you are importing the plugin, something like:

```
import annotationPlugin from 'chartjs-plugin-annotation';
```

If yes, use `annotationPlugin` instance instead

**Comment by evenmind** [comment]
> If yes, use `annotationPlugin` instance instead
Works ! Thank you.
