### ISSUE TITLE
Issue with AnnotationOptions type in 2.2.0 version

### ISSUE THREAD

**Issue by dperera-innerspec** [chartjs/chartjs-plugin-annotation#866]
With the latest version of AnnotationOptions type the library is requiring an 'init' function property. This function seems to be part of an internal class of some sort when creating a Box type annotation.

This same issue is not happening in earlier versions so i am stuck at version 2.1.2 until it is fixed.

**Comment by stockiNail** [comment]
@dperera-innerspec thank you! PR to fix is already submitted: https://github.com/chartjs/chartjs-plugin-annotation/pull/867
