### ISSUE TITLE
The mouse did not enter the box, but an event occurs.

### ISSUE THREAD

**Issue by feents** [chartjs/chartjs-plugin-annotation#879]
1. Connect to "https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/interaction/interaction.html"

2. On the "Config" tab, add "interaction: {intersect: false}", within "options".

3. Try triggering a mouse event on the chart above.

The mouse did not enter the box, but an event occurs.

**Comment by feents** [comment]
I need "interaction: { mode: 'index', intersect: false }" option to my page.

Is there any way to change the option of "interaction" in "chartjs-plugin-annotation" separately?

For example
`new Chart(document.getElementById('dataChart'), {
  type: 'line',
  data: { labels: labels, datasets: datasets },
  options: {
    ...
    interaction: { mode: 'index', intersect: false },
    ...
    annotation: {
        {
          type: "box"
          , interaction: { intersect: true }, // like this
          , xMin: 10
          , xMax: 15
          , backgroundColor: "rgba(255, 0, 0, 0.3)"
          , borderWidth: 0
          , click: (({element})=>{
            ...
          })
          , enter: (({element})=>{
            ...
            return true;
          })
          , leave: (({element})=>{
            ...
            return true;
          })
        }
      ]
    }
});`

**Comment by stockiNail** [comment]
@feents the interaction can be set at plugin level and used only for annotations. See the documentation: https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/configuration.html

Anyway interaction config cannot be set at annotation level (as you wrote above) but at plugin one and used for all annotations.
You updated code:

```javascript
new Chart(document.getElementById('dataChart'), {
  type: 'line',
  data: { labels: labels, datasets: datasets },
  options: {
    ...
    interaction: { mode: 'index', intersect: false },
    ...
    annotation: {
      interaction: { intersect: true }, // at plugin level
      annotations: [{
        type: "box"
        , xMin: 10
        , xMax: 15
        , backgroundColor: "rgba(255, 0, 0, 0.3)"
        , borderWidth: 0
        , click: (({element})=>{
          ...
        })
        , enter: (({element})=>{
          ...
          return true;
        })
        , leave: (({element})=>{
          ...
          return true;
        })
      }
    ]}
  }
});
```

**Comment by feents** [comment]
Thank you.
It works for me.

**Comment by stockiNail** [comment]
Glad to hear that!
