### ISSUE TITLE
annotation in radar charts 

### ISSUE THREAD

**Issue by satyammishra0** [chartjs/chartjs-plugin-annotation#913]
I have a radar chart created with radar charts and i have created 14 radial lines and i am seeing ticks values in the first radial like [0,50,100] now i want to show different different labels and ticks in each radial. I am attaching a image also that of what type i want to show the chart please help me out i have posted the same querty in chart js official account but didn't got any helpful response and after research i found out that this can help me out but i read on website that annotation can't be applied on radar charts so if possible tell the way to make it out 

![2](https://github.com/chartjs/chartjs-plugin-annotation/assets/90090978/a2ba55fd-74c0-4e55-a4d0-8b9fd9f91edd)

**Comment by stockiNail** [comment]
@satyammishra0 well, the annotation plugin, as you have read on website, doesn't support radar charts and mainly radial scale.
Having a look to the picture, I think we could try to use the datalabels plugin: https://chartjs-plugin-datalabels.netlify.app/

**Comment by satyammishra0** [comment]
ok can you help me out more with it in figuring how we can do so ?

**Comment by satyammishra0** [comment]
I tried that too but in that also I don't think we can customize the radials values of the ticks as used in the image i have provided

**Comment by stockiNail** [comment]
@satyammishra0 let me close it. But feel free to reopen if you needed.
