### ISSUE TITLE
label text is overwritten by annotation lines

### ISSUE THREAD

**Issue by dankell** [chartjs/chartjs-plugin-annotation#94]
We're adding vertical "date markers" to our charts. It's all going well apart from where the markers are close enough for the lines to overlap the labels.

In these cases the line cuts through the labels - is there any way to bring the labels in front of the lines?

**Comment by compwright** [comment]
Not currently. If you'd like to take a crack at it, we'll entertain a PR. Thanks!

**Comment by aciccarello** [comment]
I'm encountering this as well. In our use case it happens pretty frequently as the annotated points are often close.

![Screen Shot 2020-04-27 at 4 02 47 PM](https://user-images.githubusercontent.com/11273838/80429327-b28dbe00-88a0-11ea-83cb-658008e1f500.png)

**Comment by Veda-cmd** [comment]
Any update on this?
![Capture](https://user-images.githubusercontent.com/17611173/86099541-3c424d80-bad5-11ea-9551-c5058612cdb4.PNG)

**Comment by Veda-cmd** [comment]
Any update on this? The annotation line is cutting right through the data labels
![Capture](https://user-images.githubusercontent.com/17611173/86099746-862b3380-bad5-11ea-9e0b-e16241f0fdcf.PNG)

**Comment by nerkess** [comment]
Is it coming soon?
![26](https://user-images.githubusercontent.com/36141090/112171539-3278f100-8bf4-11eb-80e6-ac6b6c4d1232.png)

**Comment by kurkle** [comment]
@nerkess it was implemented in #275 as you should see from the last line before your comment.
That was released in https://github.com/chartjs/chartjs-plugin-annotation/releases/tag/v1.0.0-beta
We are currently at beta.4
