### ISSUE TITLE
Label annotation: Impossible to place annotations outside the chart

### ISSUE THREAD

**Issue by Jp-Aubry** [chartjs/chartjs-plugin-annotation#957]
Hello,

I have a graph with several vertical lines, each with an index.  
I would have added the indexes above each vertical outside the graph with annotation `type label`. I manage to place the index fingers inside but not outside. 
Can you help me? Maybe it's not possible!

**Comment by stockiNail** [comment]
@Jp-Aubry You need to disable the `clip` of the drawing inside the chart area.

```javascript
plugins: {
  annotation: {
    clip: false,
    annotations: { ......  }
  }
}
```

I think you could also use the "inner" label of the line annotation if you want.

Let me know

**Comment by Jp-Aubry** [comment]
it works.
I'd like to be able to add space between the text and the x-axis without having to add the x-axis. i try to add padding option but it doesnt work! 
Thanks!

**Comment by stockiNail** [comment]
You can use `yAdjust` or `xAdjust` (in pixels) to move the annotation to another center point relatively to the calculated center.

**Comment by Jp-Aubry** [comment]
I added  it and it works! Thanks for your help.
