### ISSUE TITLE
Is it possible to draw non-straight lines?

### ISSUE THREAD

**Issue by lukasz-zaroda** [chartjs/chartjs-plugin-annotation#96]
Basically I'm interested in drawing something like this (without the break) for my bar chart:

```
─┐
 └─
```
Is it possible?

**Comment by compwright** [comment]
Not currently. If you'd like to take a crack at it, we'll entertain a PR. Thanks!

**Comment by kurkle** [comment]
I think this kind of line is best drawn with line chart. You can add a line dataset in bar chart and draw any shape you like.
