### ISSUE TITLE
Annotation labels float off canvas on small screens

### ISSUE THREAD

**Issue by granttchart** [chartjs/chartjs-plugin-annotation#99]
Hello! In the current version of the plugin, annotations don't scale well on small screens, eventually floating off the chart edge. 

**Example**: https://codepen.io/grantdotlocal/pen/xPyVYJ (resize window to mobile-sized screen)

**Comment by alex-martinez** [comment]
@granttchart I had a similar issue. My interim solution is to utilize the canvas coordinates of my annotation in conjunction with the chart's chartArea coordinates. 

In your case, give your chart instance a variable. E.g. `const myChart = newChart(....);`
This will let you access the coordinates `myChart.chartArea` and `myChart.annotation.elements['some-id-0']._model`. You can then utilize these to `xAdjust` your annotation.

**Comment by etimberg** [comment]
Not exactly sure what the resolution should be here. There's no guarantee that there's enough room to draw the label

**Comment by kurkle** [comment]
In v1 the label positioning is better. We have also scriptable options for changing fort size or hiding the label or what not.
